## 将天气的数据进行清洗
## 导入新的mysql数据库
## 查找各省的疫情数据（找不全到2022年的也没关系）

In [4]:
# 将天气的数据进行清洗

import pymysql
import pandas as pd
#连接数据库
conn=pymysql.connect(host = '127.0.0.1' # 连接名称，默认127.0.0.1
,user = 'root' # 用户名
,passwd='123456' # 密码
,port= 3306 # 端口，默认为3306
,db='weibo0223' # 数据库的名字
,charset='utf8' # 字符编码
)
cur = conn.cursor() # 生成游标对象
sql="select * from `weather`  " # SQL语句
cur.execute(sql) # 执行SQL语句
data = cur.fetchall() # 通过fetchall方法获得数据
for i in data[:20]: # 打印输出前3条数据
    print(i)
# cur.close() # 关闭游标
# conn.close() # 关闭连接

(1352, '天津', '20190601', 21, 31, '阵雨/阴', '东南风1-2级/东南风1-2级')
(1353, '天津', '20190602', 22, 34, '阴/雷阵雨', '西南风3-4级/西南风3-4级')
(1354, '天津', '20190603', 21, 32, '多云/阴', '东南风3-4级/东南风3-4级')
(1355, '天津', '20190604', 21, 27, '雷阵雨/雷阵雨', '东风4-5级/东风4-5级')
(1356, '天津', '20190605', 19, 27, '阴/中雨', '东北风3-4级/东北风3-4级')
(1357, '天津', '20190606', 18, 24, '小雨/多云', '东北风3-4级/东北风3-4级')
(1358, '天津', '20190607', 22, 33, '多云/雷阵雨', '西南风3-4级/西南风3-4级')
(1359, '天津', '20190608', 21, 33, '阴/阴', '南风1-2级/南风1-2级')
(1360, '天津', '20190609', 20, 31, '晴/晴', '北风3-4级/北风3-4级')
(1361, '天津', '20190610', 21, 32, '晴/晴', '东南风3-4级/东南风3-4级')
(1362, '天津', '20190611', 23, 30, '晴/多云', '东南风3-4级/东南风3-4级')
(1363, '天津', '20190612', 22, 34, '多云/阴', '西南风3-4级/西南风3-4级')
(1364, '天津', '20190613', 21, 30, '雷阵雨/多云', '北风3-4级/北风3-4级')
(1365, '天津', '20190614', 22, 34, '晴/晴', '东北风1-2级/东北风1-2级')
(1366, '天津', '20190615', 21, 30, '多云/雷阵雨', '东南风3-4级/东南风3-4级')
(1367, '天津', '20190616', 20, 24, '阵雨/阴', '东风3-4级/东风3-4级')
(1368, '天津', '20190617', 22, 30, '多云/多云', '东风1-2级/东风1-2级')
(1369, '天津', '20190618', 21, 34, '阴/阴', '东南风1-2级/东南风1-2级')
(1370, '天津', '20190619', 23, 30, '阵雨/阴', '东南风3-4级/东南风3-4级')
(1371, '天津', '20190620', 24, 33, '多云/多云', '东南风1-2级/东南风1-2级')

In [5]:
list_scence_id = []
list_scence_city = []
list_scence_date = []
list_low_temperature = []
list_high_temperature = []
list_weather_type = []
list_wind = []

for items in data:
    scence_id = items[0]
    scence_city = items[1]
    scence_date = items[2]
    low_temperature = items[3]
    high_temperature = items[4]
    weather_type = items[5]
    wind= items[6]
    
#     scence_id = scence_id.strip()
    scence_city = scence_city.strip()
    scence_date = scence_date.strip()
#     low_temperature = low_temperature.strip()
#     high_temperature = high_temperature.strip()
    lweather_type = weather_type.strip()
    wind = wind.strip()
    
    
    list_scence_id.append(scence_id)
    list_scence_city.append(scence_city)
    list_scence_date.append(scence_date)
    list_low_temperature.append(low_temperature)
    list_high_temperature.append(high_temperature)
    list_weather_type.append(weather_type)
    list_wind.append(wind)
list_wind

['东南风1-2级/东南风1-2级',
 '西南风3-4级/西南风3-4级',
 '东南风3-4级/东南风3-4级',
 '东风4-5级/东风4-5级',
 '东北风3-4级/东北风3-4级',
 '东北风3-4级/东北风3-4级',
 '西南风3-4级/西南风3-4级',
 '南风1-2级/南风1-2级',
 '北风3-4级/北风3-4级',
 '东南风3-4级/东南风3-4级',
 '东南风3-4级/东南风3-4级',
 '西南风3-4级/西南风3-4级',
 '北风3-4级/北风3-4级',
 '东北风1-2级/东北风1-2级',
 '东南风3-4级/东南风3-4级',
 '东风3-4级/东风3-4级',
 '东风1-2级/东风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风3-4级/东南风3-4级',
 '东南风1-2级/东南风1-2级',
 '东南风4-5级/东南风4-5级',
 '西风1-2级/西风1-2级',
 '东南风3-4级/东南风3-4级',
 '西南风3-4级/西南风3-4级',
 '南风3-4级/南风3-4级',
 '东南风3-4级/东南风3-4级',
 '东南风3-4级/东南风3-4级',
 '西南风1-2级/西南风1-2级',
 '西北风4-5级/西北风4-5级',
 '东南风3-4级/东南风3-4级',
 '北风1-2级/北风1-2级',
 '东风3-4级/东风3-4级',
 '南风1-2级/南风1-2级',
 '南风3-4级/南风3-4级',
 '东南风3-4级/东南风3-4级',
 '北风3-4级/北风3-4级',
 '东风3-4级/东风3-4级',
 '北风1-2级/北风1-2级',
 '东北风1-2级/东北风1-2级',
 '东风3-4级/东风3-4级',
 '东北风1-2级/东北风1-2级',
 '西南风1-2级/西南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风3-4级/东南风3-4级',
 '东南风3-4级/东南风3-4级',
 '东北风3-4级/东北风3-4级',
 '东南风1-2级/东南风1-2级',
 '东南风3-4级/东南风3-4级',
 '东风1-2级/东风1-2级',
 '西南风1-2级/西南风1-2级',
 '东南风1-2级/东南风1-2级',
 '西北风1-2级/西北风1-2级',
 '西南风1-2级/西南风1-2级',
 '东南风1-2级/东南风1-2级',
 '南风1-2级/南风1-2级',
 '东南风3-4级/东南风3-4级',
 '东南风3-4级/东南风3-4级',
 '南风1-2级/南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西风1-2级/西风1-2级',
 '东北风1-2级/东北风1-2级',
 '东风3-4级/东风3-4级',
 '东南风1-2级/东南风1-2级',
 '东北风1-2级/东北风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东风1-2级/东风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东北风4-5级/东北风4-5级',
 '东北风5-6级/东北风5-6级',
 '北风3-4级/北风3-4级',
 '西北风1-2级/西北风1-2级',
 '南风1-2级/南风1-2级',
 '西北风4-5级/西北风4-5级',
 '西北风3-4级/西北风3-4级',
 '西南风1-2级/西南风1-2级',
 '南风1-2级/南风1-2级',
 '西南风3-4级/西南风3-4级',
 '西北风3-4级/西北风3-4级',
 '西北风1-2级/西北风1-2级',
 '东北风1-2级/东北风1-2级',
 '西南风1-2级/西南风1-2级',
 '南风1-2级/南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西北风4-5级/西北风4-5级',
 '西北风3-4级/西北风3-4级',
 '北风1-2级/北风1-2级',
 '西南风1-2级/西南风1-2级',
 '东南风3-4级/东南风3-4级',
 '西南风1-2级/西南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '南风1-2级/南风1-2级',
 '南风1-2级/南风1-2级',
 '西北风1-2级/西北风1-2级',
 '西南风1-2级/西南风1-2级',
 '东风1-2级/东风1-2级',
 '东北风4-5级/东北风4-5级',
 '东风1-2级/东风1-2级',
 '东南风3-4级/东南风3-4级',
 '西北风3-4级/西北风3-4级',
 '东南风1-2级/东南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东北风4-5级/东北风4-5级',
 '西南风1-2级/西南风1-2级',
 '东北风1-2级/东北风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东北风1-2级/东北风1-2级',
 '东北风1-2级/东北风1-2级',
 '西风1-2级/西风1-2级',
 '东风3-4级/东风3-4级',
 '南风1-2级/南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '西南风1-2级/西南风1-2级',
 '南风1-2级/南风1-2级',
 '南风3-4级/南风3-4级',
 '南风3-4级/南风3-4级',
 '东南风1-2级/东南风1-2级',
 '东风1-2级/东风1-2级',
 '东北风5-6级/东北风5-6级',
 '北风1-2级/北风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风3-4级/西南风3-4级',
 '南风1-2级/南风1-2级',
 '西南风3-4级/西南风3-4级',
 '南风1-2级/南风1-2级',
 '东风3-4级/东风3-4级',
 '东风3-4级/东风3-4级',
 '东北风4-5级/东北风4-5级',
 '北风3-4级/北风3-4级',
 '西风1-2级/西风1-2级',
 '西南风1-2级/西南风1-2级',
 '西风1-2级/西风1-2级',
 '东南风1-2级/东南风1-2级',
 '西南风3-4级/西南风3-4级',
 '北风3-4级/北风3-4级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '南风1-2级/南风1-2级',
 '北风4-5级/北风4-5级',
 '西北风4-5级/西北风4-5级',
 '西南风3-4级/西南风3-4级',
 '南风1-2级/南风1-2级',
 '西北风6-7级/西北风6-7级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '北风3-4级/北风3-4级',
 '东风4-5级/东风4-5级',
 '东北风1-2级/东北风1-2级',
 '东北风3-4级/东北风3-4级',
 '西风1-2级/西风1-2级',
 '东南风3-4级/东南风3-4级',
 '西南风1-2级/西南风1-2级',
 '东南风1-2级/东南风1-2级',
 '西风1-2级/西风1-2级',
 '南风1-2级/南风1-2级',
 '西北风5-6级/西北风5-6级',
 '南风1-2级/南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西北风5-6级/西北风5-6级',
 '西南风1-2级/西南风1-2级',
 '东风3-4级/东风3-4级',
 '东风3-4级/东风3-4级',
 '西北风5-6级/西北风5-6级',
 '西北风4-5级/西北风4-5级',
 '南风3-4级/南风3-4级',
 '东南风1-2级/东南风1-2级',
 '南风1-2级/南风1-2级',
 '南风1-2级/南风1-2级',
 '北风1-2级/北风1-2级',
 '北风5-6级/北风5-6级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东北风1-2级/东北风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西风3-4级/西风3-4级',
 '西北风3-4级/西北风3-4级',
 '西南风4-5级/西南风4-5级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东北风4-5级/东北风4-5级',
 '西南风1-2级/西南风1-2级',
 '北风1-2级/北风1-2级',
 '南风1-2级/南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西北风1-2级/西北风1-2级',
 '西北风4-5级/西北风4-5级',
 '南风1-2级/南风1-2级',
 '西北风4-5级/西北风4-5级',
 '东南风1-2级/东南风1-2级',
 '西南风1-2级/西南风1-2级',
 '北风1-2级/北风1-2级',
 '北风4-5级/北风4-5级',
 '南风1-2级/南风1-2级',
 '西北风3-4级/西北风3-4级',
 '西南风3-4级/西南风3-4级',
 '东南风1-2级/东南风1-2级',
 '西北风3-4级/西北风3-4级',
 '东风1-2级/东风1-2级',
 '南风1-2级/南风1-2级',
 '北风1-2级/北风1-2级',
 '西北风3-4级/西北风3-4级',
 '西南风1-2级/西南风1-2级',
 '南风1-2级/南风1-2级',
 '南风4-5级/南风4-5级',
 '西北风5-6级/西北风5-6级',
 '西南风3-4级/西南风3-4级',
 '西南风1-2级/西南风1-2级',
 '西北风1-2级/西北风1-2级',
 '西风1-2级/西风1-2级',
 '东风1-2级/东风1-2级',
 '东北风1-2级/东北风1-2级',
 '北风1-2级/北风1-2级',
 '东北风4-5级/东北风4-5级',
 '西风3-4级/西风3-4级',
 '南风1-2级/南风1-2级',
 '西北风1-2级/西北风1-2级',
 '东北风1-2级/东北风1-2级',
 '西北风1-2级/西北风1-2级',
 '西北风1-2级/西北风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东北风1-2级/东北风1-2级',
 '西风1-2级/西风1-2级',
 '西南风1-2级/西南风1-2级',
 '西北风1-2级/西北风1-2级',
 '南风1-2级/南风1-2级',
 '东南风1-2级/东南风1-2级',
 '南风1-2级/南风1-2级',
 '东风1-2级/东风1-2级',
 '东北风3-4级/东北风3-4级',
 '西南风1-2级/西南风1-2级',
 '东风1-2级/东风1-2级',
 '西北风1-2级/西北风1-2级',
 '东风1-2级/东风1-2级',
 '东北风1-2级/东北风1-2级',
 '南风1-2级/南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东南风1-2级/东南风1-2级',
 '西北风1-2级/西北风1-2级',
 '南风3-4级/南风3-4级',
 '东北风4-5级/东北风4-5级',
 '东风3-4级/东风3-4级',
 '南风1-2级/南风1-2级',
 '西风1-2级/西风1-2级',
 '东南风1-2级/东南风1-2级',
 '西风1-2级/西风1-2级',
 '东南风1-2级/东南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东北风5-6级/东北风5-6级',
 '西北风5-6级/西北风5-6级',
 '西北风4-5级/西北风4-5级',
 '西北风4-5级/西北风4-5级',
 '西南风1-2级/西南风1-2级',
 '东风3-4级/东风3-4级',
 '东南风1-2级/东南风1-2级',
 '西北风3-4级/西北风3-4级',
 '西风3-4级/西风3-4级',
 '西南风3-4级/西南风3-4级',
 '东风4-5级/东风4-5级',
 '东北风4-5级/东北风4-5级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '西南风1-2级/西南风1-2级',
 '南风3-4级/南风3-4级',
 '西北风4-5级/西北风4-5级',
 '东南风4-5级/东南风4-5级',
 '西北风5-6级/西北风5-6级',
 '北风4-5级/北风4-5级',
 '南风4-5级/南风4-5级',
 '西南风1-2级/西南风1-2级',
 '东南风3-4级/东南风3-4级',
 '东南风1-2级/东南风1-2级',
 '东北风4-5级/东北风4-5级',
 '西北风4-5级/西北风4-5级',
 '西南风4-5级/西南风4-5级',
 '东北风4-5级/东北风4-5级',
 '西南风1-2级/西南风1-2级',
 '西北风4-5级/西北风4-5级',
 '东北风4-5级/东北风4-5级',
 '西南风3-4级/西南风3-4级',
 '南风1-2级/南风1-2级',
 '西北风6-7级/西北风6-7级',
 '西北风4-5级/西北风4-5级',
 '南风4-5级/南风4-5级',
 '东北风4-5级/东北风4-5级',
 '西南风3-4级/西南风3-4级',
 '东南风3-4级/东南风3-4级',
 '西南风1-2级/西南风1-2级',
 '东南风3-4级/东南风3-4级',
 '北风4-5级/北风4-5级',
 '西北风4-5级/西北风4-5级',
 '西南风1-2级/西南风1-2级',
 '南风3-4级/南风3-4级',
 '西南风3-4级/西南风3-4级',
 '西南风1-2级/西南风1-2级',
 '西风1-2级/西风1-2级',
 '西风3-4级/西风3-4级',
 '西风3-4级/西风3-4级',
 '东南风4-5级/东南风4-5级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东南风3-4级/东南风3-4级',
 '东风4-5级/东风4-5级',
 '东南风1-2级/东南风1-2级',
 '北风1-2级/北风1-2级',
 '北风3-4级/北风3-4级',
 '东北风4-5级/东北风4-5级',
 '南风1-2级/南风1-2级',
 '南风3-4级/南风3-4级',
 '南风3-4级/南风3-4级',
 '西北风4-5级/西北风4-5级',
 '北风4-5级/北风4-5级',
 '东南风1-2级/东南风1-2级',
 '南风4-5级/南风4-5级',
 '西北风5-6级/西北风5-6级',
 '西北风5-6级/西北风5-6级',
 '西北风4-5级/西北风4-5级',
 '西北风4-5级/西北风4-5级',
 '西南风5-6级/西南风5-6级',
 '北风3-4级/北风3-4级',
 '北风1-2级/北风1-2级',
 '西北风1-2级/西北风1-2级',
 '西南风4-5级/西南风4-5级',
 '西南风4-5级/西南风4-5级',
 '西南风3-4级/西南风3-4级',
 '西南风3-4级/西南风3-4级',
 '东南风4-5级/东南风4-5级',
 '东风4-5级/东风4-5级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东风4-5级/东风4-5级',
 '东风1-2级/东风1-2级',
 '东风4-5级/东风4-5级',
 '西风3-4级/西风3-4级',
 '西北风4-5级/西北风4-5级',
 '西风4-5级/西风4-5级',
 '西北风1-2级/西北风1-2级',
 '南风3-4级/南风3-4级',
 '东南风3-4级/东南风3-4级',
 '东南风3-4级/东南风3-4级',
 '东南风1-2级/东南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西北风4-5级/西北风4-5级',
 '西南风1-2级/西南风1-2级',
 '东风3-4级/东风3-4级',
 '东风3-4级/东风3-4级',
 '西北风3-4级/西北风3-4级',
 '东北风4-5级/东北风4-5级',
 '西南风1-2级/西南风1-2级',
 '东北风4-5级/东北风4-5级',
 '南风1-2级/南风1-2级',
 '西北风4-5级/西北风4-5级',
 '南风4-5级/南风4-5级',
 '南风3-4级/南风3-4级',
 '东南风3-4级/东南风3-4级',
 '西北风4-5级/西北风4-5级',
 '南风4-5级/南风4-5级',
 '南风4-5级/南风4-5级',
 '东北风3-4级/东北风3-4级',
 '东风4-5级/东风4-5级',
 '东风4-5级/东风4-5级',
 '东南风3-4级/东南风3-4级',
 '西南风1-2级/西南风1-2级',
 '西南风4-5级/西南风4-5级',
 '南风1-2级/南风1-2级',
 '南风1-2级/南风1-2级',
 '东风4-5级/东风4-5级',
 '东南风1-2级/东南风1-2级',
 '东南风3-4级/东南风3-4级',
 '北风3-4级/北风3-4级',
 '西南风1-2级/西南风1-2级',
 '南风1-2级/南风1-2级',
 '西南风4-5级/西南风4-5级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风4-5级/西南风4-5级',
 '南风3-4级/南风3-4级',
 '南风3-4级/南风3-4级',
 '东南风3-4级/东南风3-4级',
 '东风3-4级/东风3-4级',
 '东南风3-4级/东南风3-4级',
 '东南风1-2级/东南风1-2级',
 '东南风3-4级/东南风3-4级',
 '东南风3-4级/东南风3-4级',
 '东风3-4级/东风3-4级',
 '西南风1-2级/西南风1-2级',
 '西南风3-4级/西南风3-4级',
 '东南风3-4级/东南风3-4级',
 '东南风3-4级/东南风3-4级',
 '西南风3-4级/西南风3-4级',
 '西南风3-4级/西南风3-4级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东北风3-4级/东北风3-4级',
 '东南风3-4级/东南风3-4级',
 '东风1-2级/东风1-2级',
 '东南风1-2级/东南风1-2级',
 '东风1-2级/东风1-2级',
 '东风1-2级/东风1-2级',
 '东南风1-2级/东南风1-2级',
 '西风1-2级/西风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风3-4级/西南风3-4级',
 '南风3-4级/南风3-4级',
 '东风3-4级/东风3-4级',
 '北风3-4级/北风3-4级',
 '西南风3-4级/西南风3-4级',
 '东南风3-4级/东南风3-4级',
 '东南风3-4级/东南风3-4级',
 '东北风3-4级/东北风3-4级',
 '西北风3-4级/西北风3-4级',
 '西南风3-4级/西南风3-4级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风3-4级/东南风3-4级',
 '南风1-2级/南风1-2级',
 '西南风3-4级/西南风3-4级',
 '南风3-4级/南风3-4级',
 '西南风1-2级/西南风1-2级',
 '南风1-2级/南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东风1-2级/东风1-2级',
 '东南风1-2级/东南风1-2级',
 '东风3-4级/东风3-4级',
 '东南风1-2级/东南风1-2级',
 '南风1-2级/南风1-2级',
 '西南风1-2级/西南风1-2级',
 '南风1-2级/南风1-2级',
 '东南风3-4级/东南风3-4级',
 '南风1-2级/南风1-2级',
 '西南风3-4级/西南风3-4级',
 '东北风3-4级/东北风3-4级',
 '北风1-2级/北风1-2级',
 '西南风1-2级/西南风1-2级',
 '西北风3-4级/西北风3-4级',
 '东北风3-4级/东北风3-4级',
 '东北风3-4级/东北风3-4级',
 '东风1-2级/东风1-2级',
 '南风1-2级/南风1-2级',
 '南风1-2级/南风1-2级',
 '北风1-2级/北风1-2级',
 '南风1-2级/南风1-2级',
 '东北风3-4级/东北风3-4级',
 '东北风1-2级/东北风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '南风1-2级/南风1-2级',
 '西北风1-2级/西北风1-2级',
 '西北风1-2级/西北风1-2级',
 '北风3-4级/北风3-4级',
 '西北风1-2级/西北风1-2级',
 '西南风1-2级/西南风1-2级',
 '东北风1-2级/东北风1-2级',
 '东南风1-2级/东南风1-2级',
 '北风3-4级/北风3-4级',
 '西北风1-2级/西北风1-2级',
 '北风3-4级/北风3-4级',
 '北风3-4级/北风3-4级',
 '北风3-4级/北风3-4级',
 '东北风3-4级/东北风3-4级',
 '东南风1-2级/东南风1-2级',
 '东南风3-4级/东南风3-4级',
 '西南风3-4级/西南风3-4级',
 '西北风3-4级/西北风3-4级',
 '西风3-4级/西风3-4级',
 '北风1-2级/北风1-2级',
 '东风1-2级/东风1-2级',
 '东南风1-2级/东南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东北风1-2级/东北风1-2级',
 '东北风1-2级/东北风1-2级',
 '东北风1-2级/东北风1-2级',
 '东北风1-2级/东北风1-2级',
 '东风1-2级/东风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东北风3-4级/东北风3-4级',
 '东南风1-2级/东南风1-2级',
 '西南风3-4级/西南风3-4级',
 '西北风1-2级/西北风1-2级',
 '西南风3-4级/西南风3-4级',
 '西北风3-4级/西北风3-4级',
 '北风1-2级/北风1-2级',
 '西南风1-2级/西南风1-2级',
 '南风1-2级/南风1-2级',
 '东南风1-2级/东南风1-2级',
 '南风1-2级/南风1-2级',
 '西南风1-2级/西南风1-2级',
 '北风3-4级/北风3-4级',
 '西北风1-2级/西北风1-2级',
 '北风3-4级/北风3-4级',
 '南风1-2级/南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西北风3-4级/西北风3-4级',
 '西南风1-2级/西南风1-2级',
 '西风1-2级/西风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风3-4级/西南风3-4级',
 '西北风3-4级/西北风3-4级',
 '西北风3-4级/西北风3-4级',
 '西北风1-2级/西北风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风4-5级/西南风4-5级',
 '西北风3-4级/西北风3-4级',
 '北风1-2级/北风1-2级',
 '西南风1-2级/西南风1-2级',
 '南风1-2级/南风1-2级',
 '西北风1-2级/西北风1-2级',
 '北风3-4级/北风3-4级',
 '西北风3-4级/西北风3-4级',
 '西北风1-2级/西北风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西北风3-4级/西北风3-4级',
 '西北风4-5级/西北风4-5级',
 '西北风1-2级/西北风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '北风3-4级/北风3-4级',
 '东南风1-2级/东南风1-2级',
 '南风1-2级/南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东风1-2级/东风1-2级',
 '南风1-2级/南风1-2级',
 '东北风4-5级/东北风4-5级',
 '东北风3-4级/东北风3-4级',
 '西风1-2级/西风1-2级',
 '北风3-4级/北风3-4级',
 '西北风1-2级/西北风1-2级',
 '西北风3-4级/西北风3-4级',
 '西南风1-2级/西南风1-2级',
 '北风3-4级/北风3-4级',
 '东风3-4级/东风3-4级',
 '北风1-2级/北风1-2级',
 '北风1-2级/北风1-2级',
 '西北风3-4级/西北风3-4级',
 '北风1-2级/北风1-2级',
 '西南风1-2级/西南风1-2级',
 '西北风3-4级/西北风3-4级',
 '西北风3-4级/西北风3-4级',
 '西北风3-4级/西北风3-4级',
 '西北风3-4级/西北风3-4级',
 '东南风1-2级/东南风1-2级',
 '西北风3-4级/西北风3-4级',
 '西北风3-4级/西北风3-4级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '西北风3-4级/西北风3-4级',
 '西风1-2级/西风1-2级',
 '南风1-2级/南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '北风3-4级/北风3-4级',
 '西南风1-2级/西南风1-2级',
 '西北风1-2级/西北风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西北风3-4级/西北风3-4级',
 '西北风1-2级/西北风1-2级',
 '南风1-2级/南风1-2级',
 '西北风1-2级/西北风1-2级',
 '东风1-2级/东风1-2级',
 '东北风3-4级/东北风3-4级',
 '西北风4-5级/西北风4-5级',
 '西北风3-4级/西北风3-4级',
 '西北风1-2级/西北风1-2级',
 '东北风1-2级/东北风1-2级',
 '北风1-2级/北风1-2级',
 '东北风1-2级/东北风1-2级',
 '北风1-2级/北风1-2级',
 '西南风3-4级/西南风3-4级',
 '西北风5-6级/西北风5-6级',
 '西北风3-4级/西北风3-4级',
 '西北风3-4级/西北风3-4级',
 '西风3-4级/西风3-4级',
 '北风1-2级/北风1-2级',
 '西北风1-2级/西北风1-2级',
 '西南风1-2级/西南风1-2级',
 '北风3-4级/北风3-4级',
 '东风3-4级/东风3-4级',
 '北风3-4级/北风3-4级',
 '西北风3-4级/西北风3-4级',
 '西南风3-4级/西南风3-4级',
 '东南风3-4级/东南风3-4级',
 '东南风3-4级/东南风3-4级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东风1-2级/东风1-2级',
 '南风1-2级/南风1-2级',
 '东南风1-2级/东南风1-2级',
 '南风1-2级/南风1-2级',
 '西北风3-4级/西北风3-4级',
 '西南风4-5级/西南风4-5级',
 '西北风3-4级/西北风3-4级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '西南风3-4级/西南风3-4级',
 '北风4-5级/北风4-5级',
 '西南风1-2级/西南风1-2级',
 '西北风3-4级/西北风3-4级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '北风3-4级/北风3-4级',
 '东风1-2级/东风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西风1-2级/西风1-2级',
 '西南风1-2级/西南风1-2级',
 '东北风1-2级/东北风1-2级',
 '东北风3-4级/东北风3-4级',
 '东风3-4级/东风3-4级',
 '西南风3-4级/西南风3-4级',
 '北风4-5级/北风4-5级',
 '西北风1-2级/西北风1-2级',
 '西南风1-2级/西南风1-2级',
 '西风1-2级/西风1-2级',
 '西南风3-4级/西南风3-4级',
 '西北风3-4级/西北风3-4级',
 '东北风3-4级/东北风3-4级',
 '东南风3-4级/东南风3-4级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东北风1-2级/东北风1-2级',
 '西南风1-2级/西南风1-2级',
 '东北风3-4级/东北风3-4级',
 '东北风1-2级/东北风1-2级',
 '南风1-2级/南风1-2级',
 '西南风3-4级/西南风3-4级',
 '西南风1-2级/西南风1-2级',
 '东北风3-4级/东北风3-4级',
 '东北风1-2级/东北风1-2级',
 '西南风1-2级/西南风1-2级',
 '南风1-2级/南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风3-4级/西南风3-4级',
 '南风1-2级/南风1-2级',
 '东风3-4级/东风3-4级',
 '西南风1-2级/西南风1-2级',
 '南风3-4级/南风3-4级',
 '北风5-6级/北风5-6级',
 '东南风3-4级/东南风3-4级',
 '东南风1-2级/东南风1-2级',
 '东风1-2级/东风1-2级',
 '南风1-2级/南风1-2级',
 '西北风4-5级/西北风4-5级',
 '西北风1-2级/西北风1-2级',
 '西南风3-4级/西南风3-4级',
 '西南风3-4级/西南风3-4级',
 '北风3-4级/北风3-4级',
 '西南风1-2级/西南风1-2级',
 '西南风3-4级/西南风3-4级',
 '东南风4-5级/东南风4-5级',
 '西北风4-5级/西北风4-5级',
 '西风1-2级/西风1-2级',
 '西南风1-2级/西南风1-2级',
 '东风3-4级/东风3-4级',
 '东风3-4级/东风3-4级',
 '东风3-4级/东风3-4级',
 '东北风1-2级/东北风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风3-4级/东南风3-4级',
 '东南风1-2级/东南风1-2级',
 '东风3-4级/东风3-4级',
 '西南风3-4级/西南风3-4级',
 '南风1-2级/南风1-2级',
 '西北风3-4级/西北风3-4级',
 '西北风3-4级/西北风3-4级',
 '西南风3-4级/西南风3-4级',
 '西北风5-6级/西北风5-6级',
 '西风3-4级/西风3-4级',
 '西北风4-5级/西北风4-5级',
 '西南风3-4级/西南风3-4级',
 '西南风1-2级/西南风1-2级',
 '东南风3-4级/东南风3-4级',
 '东南风1-2级/东南风1-2级',
 '东北风1-2级/东北风1-2级',
 '东北风3-4级/东北风3-4级',
 '东风1-2级/东风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风3-4级/东南风3-4级',
 '西北风4-5级/西北风4-5级',
 '西南风3-4级/西南风3-4级',
 '西北风4-5级/西北风4-5级',
 '北风3-4级/北风3-4级',
 '北风1-2级/北风1-2级',
 '南风3-4级/南风3-4级',
 '南风3-4级/南风3-4级',
 '西北风4-5级/西北风4-5级',
 '西南风4-5级/西南风4-5级',
 '西南风5-6级/西南风5-6级',
 '西北风4-5级/西北风4-5级',
 '西北风3-4级/西北风3-4级',
 '东南风3-4级/东南风3-4级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东风1-2级/东风1-2级',
 '东南风1-2级/东南风1-2级',
 '东北风3-4级/东北风3-4级',
 '西北风1-2级/西北风1-2级',
 '西南风3-4级/西南风3-4级',
 '西南风3-4级/西南风3-4级',
 '南风3-4级/南风3-4级',
 '南风1-2级/南风1-2级',
 '西南风1-2级/西南风1-2级',
 '南风3-4级/南风3-4级',
 '西北风3-4级/西北风3-4级',
 '西北风3-4级/西北风3-4级',
 '西南风4-5级/西南风4-5级',
 '东北风1-2级/东北风1-2级',
 '西南风4-5级/西南风4-5级',
 '西北风3-4级/西北风3-4级',
 '东风3-4级/东风3-4级',
 '东南风1-2级/东南风1-2级',
 '东风1-2级/东风1-2级',
 '东南风1-2级/东南风1-2级',
 '北风3-4级/北风3-4级',
 '西北风3-4级/西北风3-4级',
 '西北风1-2级/西北风1-2级',
 '西北风1-2级/西北风1-2级',
 '西北风1-2级/西北风1-2级',
 '西北风1-2级/西北风1-2级',
 '东风3-4级/东风3-4级',
 '东风3-4级/东风3-4级',
 '东南风1-2级/东南风1-2级',
 '东风3-4级/东风3-4级',
 '东北风1-2级/东北风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风3-4级/东南风3-4级',
 '东南风1-2级/东南风1-2级',
 '北风3-4级/北风3-4级',
 '西北风1-2级/西北风1-2级',
 '西南风3-4级/西南风3-4级',
 '西北风1-2级/西北风1-2级',
 '东风3-4级/东风3-4级',
 '东风1-2级/东风1-2级',
 '东南风3-4级/东南风3-4级',
 '东风1-2级/东风1-2级',
 '西南风1-2级/西南风1-2级',
 '南风1-2级/南风1-2级',
 '东北风1-2级/东北风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风3-4级/东南风3-4级',
 '南风3-4级/南风3-4级',
 '东南风3-4级/东南风3-4级',
 '南风1-2级/南风1-2级',
 '西风1-2级/西风1-2级',
 '东南风1-2级/东南风1-2级',
 '南风1-2级/南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '南风1-2级/南风1-2级',
 '东南风3-4级/东南风3-4级',
 '东南风3-4级/东南风3-4级',
 '东南风4-5级/东南风4-5级',
 '西南风3-4级/西南风3-4级',
 '东南风1-2级/东南风1-2级',
 '东风3-4级/东风3-4级',
 '东风3-4级/东风3-4级',
 '东南风3-4级/东南风3-4级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东风1-2级/东风1-2级',
 '东南风1-2级/东南风1-2级',
 '东风1-2级/东风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '南风3-4级/南风3-4级',
 '东南风1-2级/东南风1-2级',
 '东北风1-2级/东北风1-2级',
 '东北风4-5级/东北风4-5级',
 '西北风3-4级/西北风3-4级',
 '南风1-2级/南风1-2级',
 '北风1-2级/北风1-2级',
 '东北风3-4级/东北风3-4级',
 '东南风1-2级/东南风1-2级',
 '南风1-2级/南风1-2级',
 '南风1-2级/南风1-2级',
 '西风1-2级/西风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西风1-2级/西风1-2级',
 '东北风1-2级/东北风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东风1-2级/东风1-2级',
 '东南风1-2级/东南风1-2级',
 '南风1-2级/南风1-2级',
 '北风1-2级/北风1-2级',
 '南风1-2级/南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东南风1-2级/东南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西风3-4级/西风3-4级',
 '西北风1-2级/西北风1-2级',
 '北风1-2级/北风1-2级',
 '西风1-2级/西风1-2级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东北风1-2级/东北风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '南风1-2级/南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东风3-4级/东风3-4级',
 '北风3-4级/北风3-4级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '南风1-2级/南风1-2级',
 '东南风1-2级/东南风1-2级',
 '南风1-2级/南风1-2级',
 '东南风3-4级/东南风3-4级',
 '东北风3-4级/东北风3-4级',
 '东风3-4级/东风3-4级',
 '东风1-2级/东风1-2级',
 '北风1-2级/北风1-2级',
 '东北风1-2级/东北风1-2级',
 '西南风1-2级/西南风1-2级',
 '东北风3-4级/东北风3-4级',
 '北风4-5级/北风4-5级',
 '西北风3-4级/西北风3-4级',
 '西北风1-2级/西北风1-2级',
 '东风3-4级/东风3-4级',
 '东风3-4级/东风3-4级',
 '东南风1-2级/东南风1-2级',
 '东风1-2级/东风1-2级',
 '北风1-2级/北风1-2级',
 '南风1-2级/南风1-2级',
 '东北风1-2级/东北风1-2级',
 '东北风3-4级/东北风3-4级',
 '东北风1-2级/东北风1-2级',
 '南风1-2级/南风1-2级',
 '东风3-4级/东风3-4级',
 '北风3-4级/北风3-4级',
 '东北风3-4级/东北风3-4级',
 '北风1-2级/北风1-2级',
 '北风1-2级/北风1-2级',
 '东南风1-2级/东南风1-2级',
 '北风3-4级/北风3-4级',
 '西北风3-4级/西北风3-4级',
 '西北风1-2级/西北风1-2级',
 '西北风1-2级/西北风1-2级',
 '西南风1-2级/西南风1-2级',
 '西北风1-2级/西北风1-2级',
 '北风4-5级/北风4-5级',
 '北风1-2级/北风1-2级',
 '西南风3-4级/西南风3-4级',
 '东北风3-4级/东北风3-4级',
 '东北风3-4级/东北风3-4级',
 '西南风1-2级/西南风1-2级',
 '西北风3-4级/西北风3-4级',
 '北风1-2级/北风1-2级',
 '南风1-2级/南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西北风3-4级/西北风3-4级',
 '西风1-2级/西风1-2级',
 '西南风1-2级/西南风1-2级',
 '东南风1-2级/东南风1-2级',
 '西风1-2级/西风1-2级',
 '东北风1-2级/东北风1-2级',
 '东北风1-2级/东北风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '南风1-2级/南风1-2级',
 '东风4-5级/东风4-5级',
 '北风4-5级/北风4-5级',
 '西北风4-5级/西北风4-5级',
 '西北风3-4级/西北风3-4级',
 '西北风3-4级/西北风3-4级',
 '西北风3-4级/西北风3-4级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风3-4级/西南风3-4级',
 '北风1-2级/北风1-2级',
 '东南风1-2级/东南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东风3-4级/东风3-4级',
 '东北风1-2级/东北风1-2级',
 '东北风1-2级/东北风1-2级',
 '西北风4-5级/西北风4-5级',
 '西北风1-2级/西北风1-2级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东北风1-2级/东北风1-2级',
 '东南风1-2级/东南风1-2级',
 '南风1-2级/南风1-2级',
 '北风3-4级/北风3-4级',
 '西北风4-5级/西北风4-5级',
 '西南风1-2级/西南风1-2级',
 '西风1-2级/西风1-2级',
 '西南风1-2级/西南风1-2级',
 '南风1-2级/南风1-2级',
 '西南风3-4级/西南风3-4级',
 '北风3-4级/北风3-4级',
 '西南风1-2级/西南风1-2级',
 '南风1-2级/南风1-2级',
 '西风1-2级/西风1-2级',
 '西北风3-4级/西北风3-4级',
 '西北风3-4级/西北风3-4级',
 '北风1-2级/北风1-2级',
 '西南风1-2级/西南风1-2级',
 '南风1-2级/南风1-2级',
 '南风1-2级/南风1-2级',
 '西北风4-5级/西北风4-5级',
 '西北风4-5级/西北风4-5级',
 '西风3-4级/西风3-4级',
 '西南风1-2级/西南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东风3-4级/东风3-4级',
 '东北风1-2级/东北风1-2级',
 '东风3-4级/东风3-4级',
 '东北风3-4级/东北风3-4级',
 '西北风3-4级/西北风3-4级',
 '西北风3-4级/西北风3-4级',
 '西南风1-2级/西南风1-2级',
 '西南风3-4级/西南风3-4级',
 '北风3-4级/北风3-4级',
 '西风1-2级/西风1-2级',
 '西南风1-2级/西南风1-2级',
 '西北风4-5级/西北风4-5级',
 '南风1-2级/南风1-2级',
 '北风1-2级/北风1-2级',
 '东南风1-2级/东南风1-2级',
 '北风1-2级/北风1-2级',
 '东南风1-2级/东南风1-2级',
 '西南风1-2级/西南风1-2级',
 '北风1-2级/北风1-2级',
 '东南风1-2级/东南风1-2级',
 '北风3-4级/北风3-4级',
 '东南风1-2级/东南风1-2级',
 '西北风3-4级/西北风3-4级',
 '西南风1-2级/西南风1-2级',
 '西南风3-4级/西南风3-4级',
 '北风3-4级/北风3-4级',
 '南风1-2级/南风1-2级',
 '西北风3-4级/西北风3-4级',
 '南风3-4级/南风3-4级',
 '东北风3-4级/东北风3-4级',
 '东南风1-2级/东南风1-2级',
 '东南风1-2级/东南风1-2级',
 '东北风1-2级/东北风1-2级',
 '东风1-2级/东风1-2级',
 '西南风1-2级/西南风1-2级',
 '西北风3-4级/西北风3-4级',
 '东北风1-2级/东北风1-2级',
 '北风1-2级/北风1-2级',
 '北风1-2级/北风1-2级',
 '东南风1-2级/东南风1-2级',
 '南风1-2级/南风1-2级',
 '西北风4-5级/西北风4-5级',
 '西北风1-2级/西北风1-2级',
 '北风1-2级/北风1-2级',
 '北风1-2级/北风1-2级',
 '西北风3-4级/西北风3-4级',
 '西北风3-4级/西北风3-4级',
 '北风1-2级/北风1-2级',
 '东北风1-2级/东北风1-2级',
 '西北风1-2级/西北风1-2级',
 '南风1-2级/南风1-2级',
 '西南风1-2级/西南风1-2级',
 '东北风3-4级/东北风3-4级',
 '东风3-4级/东风3-4级',
 '东北风3-4级/东北风3-4级',
 '北风1-2级/北风1-2级',
 '北风1-2级/北风1-2级',
 '北风1-2级/北风1-2级',
 '东南风1-2级/东南风1-2级',
 '西风1-2级/西风1-2级',
 '西北风1-2级/西北风1-2级',
 ...]

In [6]:
dict_weather = {}
data_weather = pd.DataFrame(dict_weather)

data_weather['scence_id'] = list_scence_id 
data_weather['scence_city'] = list_scence_city 
data_weather['scence_date'] = list_scence_date 
data_weather['low_temperature'] = list_low_temperature 
data_weather['high_temperature'] = list_high_temperature 
data_weather['weather_type'] = list_weather_type 
data_weather['wind'] = list_wind 

data_weather

,scence_id,scence_city,scence_date,low_temperature,high_temperature,weather_type,wind
0,1352,天津,20190601,21,31,阵雨/阴,东南风1-2级/东南风1-2级
1,1353,天津,20190602,22,34,阴/雷阵雨,西南风3-4级/西南风3-4级
2,1354,天津,20190603,21,32,多云/阴,东南风3-4级/东南风3-4级
3,1355,天津,20190604,21,27,雷阵雨/雷阵雨,东风4-5级/东风4-5级
4,1356,天津,20190605,19,27,阴/中雨,东北风3-4级/东北风3-4级
...,...,...,...,...,...,...,...
231435,251002,呼伦贝尔,20221227,-27,-21,多云/小雪,西北风1-2级/西北风1-2级
231436,251003,呼伦贝尔,20221228,-32,-22,小雪/晴,西风3-4级/西风3-4级
231437,251004,呼伦贝尔,20221229,-30,-21,晴/晴,西风3-4级/西风1-2级
231438,251005,呼伦贝尔,20221230,-26,-16,晴/晴,西南风3-4级/西风3-4级
231439,251006,呼伦贝尔,20221231,-30,-19,晴/晴,西风3-4级/西风3-4级

In [7]:
count1 = 0
for i in data_weather['weather_type']:
    if '/' in i:
        count1+=1
    else:
        continue
count1

231440

In [8]:
list_weather1 = []
list_weather2 = []
for items in data_weather['weather_type']:
    weather1, weather2 = items.split('/')
    list_weather1.append(weather1)
    list_weather2.append(weather2)
data_weather['weather1'] = list_weather1
data_weather['weather2'] = list_weather2
data_weather

,scence_id,scence_city,scence_date,low_temperature,high_temperature,weather_type,wind,weather1,weather2
0,1352,天津,20190601,21,31,阵雨/阴,东南风1-2级/东南风1-2级,阵雨,阴
1,1353,天津,20190602,22,34,阴/雷阵雨,西南风3-4级/西南风3-4级,阴,雷阵雨
2,1354,天津,20190603,21,32,多云/阴,东南风3-4级/东南风3-4级,多云,阴
3,1355,天津,20190604,21,27,雷阵雨/雷阵雨,东风4-5级/东风4-5级,雷阵雨,雷阵雨
4,1356,天津,20190605,19,27,阴/中雨,东北风3-4级/东北风3-4级,阴,中雨
...,...,...,...,...,...,...,...,...,...
231435,251002,呼伦贝尔,20221227,-27,-21,多云/小雪,西北风1-2级/西北风1-2级,多云,小雪
231436,251003,呼伦贝尔,20221228,-32,-22,小雪/晴,西风3-4级/西风3-4级,小雪,晴
231437,251004,呼伦贝尔,20221229,-30,-21,晴/晴,西风3-4级/西风1-2级,晴,晴
231438,251005,呼伦贝尔,20221230,-26,-16,晴/晴,西南风3-4级/西风3-4级,晴,晴
231439,251006,呼伦贝尔,20221231,-30,-19,晴/晴,西风3-4级/西风3-4级,晴,晴

In [9]:
# 将天气的数据进行存储
# E:\论文\第二篇论文\截止到2023年2月数据汇总
data_weather.to_csv('E:\\论文\\第二篇论文\\截止到2023年2月数据汇总\\天气的总数据.csv',encoding = 'utf-8-sig')

## 上面. 天气的数据构建的dataframe为data_weather
## 下面. 将剩余的数据进行情感得分统计

In [10]:
# 链接数据库
import pymysql
import pandas as pd
#连接数据库
conn=pymysql.connect(host = '127.0.0.1' # 连接名称，默认127.0.0.1
,user = 'root' # 用户名
,passwd='123456' # 密码
,port= 3306 # 端口，默认为3306
,db='weibo0223' # 数据库名称
,charset='utf8' # 字符编码
)
cur = conn.cursor() # 生成游标对象
sql="select * from `post`  " # SQL语句
cur.execute(sql) # 执行SQL语句
data2 = cur.fetchall() # 通过fetchall方法获得数据
for i in data2[:20]: # 打印输出前3条数据
    print(i)
# cur.close() # 关闭游标
# conn.close() # 关闭连接
print(len(data2))

(1, '圆明园', 'SUNXIN666666', '2023-01-12 18:59', '', '2023/1/12 22:04:19')
(2, '圆明园', '第七十七天的凤梨罐头', '2023-01-12 20:04', '百京初雪诚不欺我<br>冬天的圆明园更有萧瑟感，直出都敲好看', '2023/1/12 22:04:19')
(3, '圆明园', 'Firrts', '2023-01-12 19:59', '', '2023/1/12 22:04:19')
(4, '圆明园', 'big小南', '2023-01-12 13:06', '<br>存图日记', '2023/1/12 22:04:19')
(5, '圆明园', '约我散步', '2023-01-12 21:13', '见到了历史书上的圆明园', '2023/1/12 22:04:19')
(6, '圆明园', 'jiajiafighting888', '2023-01-12 19:41', '初雪', '2023/1/12 22:04:19')
(7, '圆明园', '易家二十_28', '2023-01-12 15:33', '下雪啦', '2023/1/12 22:04:19')
(8, '圆明园', 'NickelCu', '2023-01-12 16:16', '分享图片', '2023/1/12 22:04:19')
(9, '圆明园', '王者酷行', '2023-01-11 23:04', '冬日里逛圆明园有一个其他季节得不到的好处，等湖面完全结冰后，就可以去以往划船也无法企及的小岛，人总是对于平常日子得不到的东西充满期待，所以就觉得那是冬日里的赏赐', '2023/1/12 22:04:19')
(10, '圆明园', '会水的小平', '2023-01-12 10:52', '分享图片', '2023/1/12 22:04:19')
(11, '圆明园', '劝你放下那块小饼干', '2023-01-11 19:28', '看着这些被破坏的作品<br>心里很不是滋味', '2023/1/12 22:04:19')
(12, '圆明园', 'Holiday--潇', '2023-01-12 09:00', '圆明园喂天鹅', '2023/1/12 22:04:19')
(13, '圆明园', '终始本末', '2023-01-12 17:06', '偶遇圆明园的雪景', '2023/1/12 22:04:19')
(14, '圆明园', 'So-毒生', '2023-01-11 09:01', '不限号本来就已经很堵车了，早高峰的北五环还要天天封一条路查车。我不太理解这个操作，能不能出来讲两句？我求你们了，别给群众添堵了', '2023/1/12 22:04:19')
(15, '圆明园', '时间与意识的羔羊', '2023-01-12 01:45', '金鬃马 电镀的肺 湖光的景 最闪亮的基因', '2023/1/12 22:04:19')
(16, '圆明园', 'i林深不见鹿呀', '2023-01-11 07:49', '昔日皇家园林<br>', '2023/1/12 22:04:19')
(17, '圆明园', 'Lucky-ADLA', '2023-01-11 18:08', '分享图片', '2023/1/12 22:04:19')
(18, '圆明园', '刘撑撑', '2023-01-11 13:18', '3亿人上冰雪？什刹海被几百米的队伍劝退，颐和园干脆停车场都没进去。最终在圆明园好不容易是上去了，然鹅冰面开化，滑三下卡一下。明年一定得做早起的鸟儿了。', '2023/1/12 22:04:19')
(19, '圆明园', 'Rvvvvi', '2023-01-11 18:24', '快步疾走', '2023/1/12 22:04:19')
(20, '圆明园', '鑫鑫_623', '2023-01-11 17:49', '满是遗憾<br>站在圆明园的西洋楼遗址前，短暂失语……', '2023/1/12 22:04:19')
96652

In [11]:
# # 选取前十个调试
# data_10 = data[:10]
# 全部数据
data_10 = data2
import pandas as pd
# list_data = list(data_10)
def tuple_to_list(t1):
    return list(t1)
list_data = list(map(tuple_to_list,data_10))
len(list_data)

96652

In [12]:
def split_data(list1):
    string1 = str(list1)
    list2 = string1.split(',')
    return list2
    
data_list_all = list(map(split_data,list_data))
#data_list_all
len(data_list_all)

96652

In [13]:
#### - comment_id: 0
#### - scence_name:1
#### - user_name:2
#### - comment_time:3
#### - comment_detail:4
#### - crawl_time:-1
# 将list换分为新list
list_comment_id = []
list_scence_name = []
list_user_name = []
list_comment_time = []
list_comment_detail = []
list_crawl_time = []

for list1 in data_list_all:
    string0 = str(list1[0]).replace('[','')
    string0 = int(string0)
    # 清洗comment_id数据,并转换为整数类型
    
    string1 = str(list1[1]).replace('\'','')
    string1 = string1.strip()
    # 清洗scence_name数据
    
    string2 = str(list1[2]).replace('\'','')
    string2 = string2.strip()
    # 清洗user_name数据   
    
    string3 = str(list1[3]).replace('\'','')
    string3 = string3.strip()
    # 清洗comment_time数据       
    
    string4 = str(list1[4]).replace('\'','')
    string4= string4.replace('<br>',' ')
    string4 = string4.strip()
    # 清洗comment_detail数据                                
    
    string_1 = str(list1[-1]).replace('\'','')
    string_1 = string_1.replace(']',' ')
    string_1 = string_1.strip()
    # 清洗crawl_time数据                                
        
    
    
    list_comment_id.append(string0) 
    list_scence_name.append(string1) 
    list_user_name.append(string2) 
    list_comment_time.append(string3)
    list_comment_detail.append(string4) 
    list_crawl_time.append(string_1) 
# 将数据转换为dataframework类型
# 构建字典
dic_new = {'comment_id':list_comment_id,
           'scence_name':list_scence_name,
           'user_name':list_user_name,
           'comment_time':list_comment_time,
           'comment_detail':list_comment_detail,
           'crawl_time':list_crawl_time}
data_new = pd.DataFrame(dic_new)
data_new

,comment_id,scence_name,user_name,comment_time,comment_detail,crawl_time
0,1,圆明园,SUNXIN666666,2023-01-12 18:59,,2023/1/12 22:04:19
1,2,圆明园,第七十七天的凤梨罐头,2023-01-12 20:04,百京初雪诚不欺我 冬天的圆明园更有萧瑟感，直出都敲好看,2023/1/12 22:04:19
2,3,圆明园,Firrts,2023-01-12 19:59,,2023/1/12 22:04:19
3,4,圆明园,big小南,2023-01-12 13:06,存图日记,2023/1/12 22:04:19
4,5,圆明园,约我散步,2023-01-12 21:13,见到了历史书上的圆明园,2023/1/12 22:04:19
...,...,...,...,...,...,...
96647,256410,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,WcKyrie,2021-05-27 15:26,,2023/1/14 01:38:20
96648,256411,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,云上旅游玩家,2019-10-08 13:08,你不去看世界 世界也懒得看你,2023/1/14 01:38:20
96649,256412,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,奥特曼被怪兽打败了,2021-03-12 00:32,伤害性不大，侮辱性极强。,2023/1/14 01:38:20
96650,256413,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,TIE_TIE_,2019-09-30 19:39,边境之景,2023/1/14 01:38:20
96651,256414,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,叁叁肆和陈畅炫,2022-06-21 21:00,分享图片,2023/1/14 01:38:20

In [14]:
def tenwords(string1):
    string2 = string1[:11]
    return string2
data_new['comment_day'] = data_new['comment_time'].apply(tenwords)
data_new_day_commentId = data_new[['comment_day','scence_name','comment_id','scence_name','comment_detail']]
data_new_day_commentId

,comment_day,scence_name,comment_id,scence_name,comment_detail
0,2023-01-12,圆明园,1,圆明园,
1,2023-01-12,圆明园,2,圆明园,百京初雪诚不欺我 冬天的圆明园更有萧瑟感，直出都敲好看
2,2023-01-12,圆明园,3,圆明园,
3,2023-01-12,圆明园,4,圆明园,存图日记
4,2023-01-12,圆明园,5,圆明园,见到了历史书上的圆明园
...,...,...,...,...,...
96647,2021-05-27,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,256410,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,
96648,2019-10-08,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,256411,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,你不去看世界 世界也懒得看你
96649,2021-03-12,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,256412,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,伤害性不大，侮辱性极强。
96650,2019-09-30,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,256413,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,边境之景
96651,2022-06-21,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,256414,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,分享图片

In [15]:
data_new = data_new_day_commentId

In [16]:

def count_chinese_words(string1):
    return len(string1)
list_comment_len = data_new['comment_detail'].apply(count_chinese_words)
data_new['comment_len'] = list_comment_len
data_new1 = data_new[(data_new['comment_len']<200) & (data_new['comment_len']>0)]
# data_new = data_new[(data_new['comment_len']>15)]



new_list_comment_detail1 = data_new1['comment_detail']
print(len(data_new1))
# print(data_new1)
# new_list_comment_detail

90247

D:\python\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [17]:
#计算
import json
from tencentcloud.common import credential
from tencentcloud.common.profile.client_profile import ClientProfile
from tencentcloud.common.profile.http_profile import HttpProfile
from tencentcloud.common.exception.tencent_cloud_sdk_exception import TencentCloudSDKException
from tencentcloud.nlp.v20190408 import nlp_client, models
list_median_sentiment = []
try:
    # 实例化一个认证对象，入参需要传入腾讯云账户secretId，secretKey,此处还需注意密钥对的保密
    # 密钥可前往https://console.cloud.tencent.com/cam/capi网站进行获取
    cred = credential.Credential("AKIDqVxB8oDMHwlLm6Bk23oCZovpVw71BBzX", "MSItEJAnBPO8d3GEwPedOu99vSEk14qM")

# SecretId: AKIDqVxB8oDMHwlLm6Bk23oCZovpVw71BBzX
# SecretKey: MSItEJAnBPO8d3GEwPedOu99vSEk14qM    
    for text1 in new_list_comment_detail1:
    # 实例化一个http选项，可选的，没有特殊需求可以跳过
        httpProfile = HttpProfile()
        httpProfile.endpoint = "nlp.tencentcloudapi.com"

    # 实例化一个client选项，可选的，没有特殊需求可以跳过
        clientProfile = ClientProfile()
        clientProfile.httpProfile = httpProfile
    # 实例化要请求产品的client对象,clientProfile是可选的
        client = nlp_client.NlpClient(cred, "ap-guangzhou", clientProfile)
    
    
        

    # 实例化一个请求对象,每个接口都会对应一个request对象
        req = models.SentimentAnalysisRequest()
        params = {
         "Text": text1,
         "Mode": "3class"
    }
        req.from_json_string(json.dumps(params))

    # 返回的resp是一个SentimentAnalysisResponse的实例，与请求对象对应
        resp = client.SentimentAnalysis(req)
        list_median_sentiment.append(resp.to_json_string())
    # 输出json格式的字符串回包
        print(resp.to_json_string())
except TencentCloudSDKException as err:
    print(err)

print('all words between 0 and 200 in compete!')

{"Positive": 0.8252176, "Neutral": 0.02819603, "Negative": 0.14661635, "Sentiment": "positive", "RequestId": "652226a9-e8df-43d8-a5e2-2a23acaf9ef7"}
{"Positive": 0.04156467, "Neutral": 0.94359624, "Negative": 0.01486912, "Sentiment": "neutral", "RequestId": "f413e31b-0fb4-4701-a127-d00a823d5c6e"}
{"Positive": 0.12664282, "Neutral": 0.86446464, "Negative": 0.00892258, "Sentiment": "neutral", "RequestId": "3262ddd4-ab02-4469-983f-21561748a78f"}
{"Positive": 0.5157764, "Neutral": 0.48370948, "Negative": 0.00054412, "Sentiment": "positive", "RequestId": "73f61936-010f-463f-9a18-0fdcc6ce360d"}
{"Positive": 0.13782555, "Neutral": 0.85944921, "Negative": 0.0027553, "Sentiment": "neutral", "RequestId": "7a7b2a59-b9fc-47ee-96ba-9aece7e01e0a"}
{"Positive": 0.00056465, "Neutral": 0.99927229, "Negative": 0.00019305, "Sentiment": "neutral", "RequestId": "ed70070e-f7dd-4346-89f1-e237d48eaf5c"}
{"Positive": 0.61022556, "Neutral": 0.20535599, "Negative": 0.18444848, "Sentiment": "positive", "RequestId": "85188649-4576-4124-8e3c-4d7ddade9084"}
{"Positive": 0.00056465, "Neutral": 0.99927229, "Negative": 0.00019305, "Sentiment": "neutral", "RequestId": "1d79b8e9-1d03-4640-898f-43bc7e5fdbdd"}
{"Positive": 0.00196909, "Neutral": 0.01058676, "Negative": 0.98747408, "Sentiment": "negative", "RequestId": "b6f89bdd-ab23-45de-9586-4d15c7e8bfe2"}
{"Positive": 0.97022915, "Neutral": 0.02923826, "Negative": 0.0005626, "Sentiment": "positive", "RequestId": "caaeb1d2-6039-40c9-82c6-cd4afeab1e0e"}
{"Positive": 0.72010201, "Neutral": 0.27913004, "Negative": 0.00079796, "Sentiment": "positive", "RequestId": "77d37ca2-c6af-42bb-a8a8-aae0b26a8af2"}
{"Positive": 0.02444732, "Neutral": 0.14042281, "Negative": 0.8351599, "Sentiment": "negative", "RequestId": "2b0a9b64-2cd0-4716-bd74-f5e2dac6e117"}
{"Positive": 0.70713246, "Neutral": 0.28381035, "Negative": 0.00908722, "Sentiment": "positive", "RequestId": "f4fa4808-f2a3-4436-98dd-d2556e12d1fb"}
{"Positive": 0.89940536, "Neutral": 0.09234078, "Negative": 0.00828392, "Sentiment": "positive", "RequestId": "8cad6bd2-ff63-42a6-a406-04d0f621a073"}
{"Positive": 0.00056465, "Neutral": 0.99927229, "Negative": 0.00019305, "Sentiment": "neutral", "RequestId": "23897aa0-de94-4824-9ec1-fc79287d8c07"}
{"Positive": 0.1991391, "Neutral": 0.23637569, "Negative": 0.56451523, "Sentiment": "negative", "RequestId": "240aa29e-5fd9-4671-a3ef-6d7db578ba98"}
{"Positive": 0.1590227, "Neutral": 0.8295486, "Negative": 0.01145863, "Sentiment": "neutral", "RequestId": "8b3a8b1d-132f-48dd-8e46-e7497be7cdd2"}
{"Positive": 0.06563414, "Neutral": 0.09554362, "Negative": 0.83885229, "Sentiment": "negative", "RequestId": "5b2b03f8-6be6-4e83-aaeb-7ddfbb5536ec"}
{"Positive": 0.2726576, "Neutral": 0.19898558, "Negative": 0.52838683, "Sentiment": "negative", "RequestId": "2ce570f6-7d09-4952-abbe-4ae694770b42"}
{"Positive": 0.47689149, "Neutral": 0.47516835, "Negative": 0.04797021, "Sentiment": "positive", "RequestId": "8f00002f-4a0e-49b3-85a0-5975824f2556"}
{"Positive": 0.99943566, "Neutral": 0.0001424, "Negative": 0.00045203, "Sentiment": "positive", "RequestId": "a7993395-ff4c-48e5-b564-fae00b938569"}
{"Positive": 0.76679236, "Neutral": 0.17732248, "Negative": 0.05591512, "Sentiment": "positive", "RequestId": "68869785-863f-4491-8f09-ea700dfba4cf"}
{"Positive": 0.71395421, "Neutral": 0.264047, "Negative": 0.0220288, "Sentiment": "positive", "RequestId": "9a107450-f59c-461d-97b0-0f368fee29a7"}
{"Positive": 0.48264804, "Neutral": 0.34532273, "Negative": 0.17205921, "Sentiment": "positive", "RequestId": "0c25bc21-596c-49df-8ff6-1dff5d8ecf07"}
{"Positive": 0.96360612, "Neutral": 0.00063607, "Negative": 0.03578785, "Sentiment": "positive", "RequestId": "a428e3f6-f3ad-43d6-aeeb-6c5595a07941"}
{"Positive": 0.00700204, "Neutral": 0.36484712, "Negative": 0.6281808, "Sentiment": "negative", "RequestId": "c4498f03-1b16-4df7-8816-1e67724b6303"}
{"Positive": 0.10126895, "Neutral": 0.88675487, "Negative": 0.01200624, "Sentiment": "neutral", "RequestId": "2357a53c-898e-4ee5-b880-c98f2b3719fe"}
{"Positive": 0.07440772, "Neutral": 0.26813808, "Negative": 0.65748423, "Sentiment": "negative", "RequestId": "ac70272a-8d31-4d2c-a276-62951e19678b"}
{"Positive": 0.00056465, "Neutral": 0.99927229, "Negative": 0.00019305, "Sentiment": "neutral", "RequestId": "8f25a04d-71b2-45ef-9104-05586200ce22"}
{"Positive": 0.70004249, "Neutral": 0.15368141, "Negative": 0.14630608, "Sentiment": "positive", "RequestId": "831963c8-4904-4ade-9b6e-a5ed3047f0b7"}
{"Positive": 0.06013334, "Neutral": 0.10479967, "Negative": 0.83509707, "Sentiment": "negative", "RequestId": "30cd9381-1ea1-438f-99ef-4d8a985946e9"}
{"Positive": 0.00056465, "Neutral": 0.99927229, "Negative": 0.00019305, "Sentiment": "neutral", "RequestId": "78650662-252a-4ea0-951b-a8e77af8c547"}
{"Positive": 0.9999764, "Neutral": 4.126e-05, "Negative": 1.241e-05, "Sentiment": "positive", "RequestId": "1286c4f4-6a39-4d01-885a-aad37570bda3"}
{"Positive": 0.00056465, "Neutral": 0.99927229, "Negative": 0.00019305, "Sentiment": "neutral", "RequestId": "1eee798e-d503-45cc-9e05-9ffe125df8b8"}
{"Positive": 0.06786691, "Neutral": 0.74686229, "Negative": 0.1853008, "Sentiment": "neutral", "RequestId": "75a111f2-6966-4daa-b815-1e37cf84c033"}
{"Positive": 0.78645903, "Neutral": 0.19684866, "Negative": 0.01672234, "Sentiment": "positive", "RequestId": "b41cc1a8-b5eb-4aae-a9d8-17a02ad3ad11"}
{"Positive": 0.27719316, "Neutral": 0.59312457, "Negative": 0.1297123, "Sentiment": "neutral", "RequestId": "4bbbdd69-b215-47d0-85bf-af1a93cc85de"}
{"Positive": 0.84522057, "Neutral": 0.15471117, "Negative": 9.827e-05, "Sentiment": "positive", "RequestId": "464f2b6e-ddea-432c-975e-b993fce99d9f"}
{"Positive": 0.00056465, "Neutral": 0.99927229, "Negative": 0.00019305, "Sentiment": "neutral", "RequestId": "f43d1882-1b7e-4a6b-936c-d6ddad096081"}
{"Positive": 0.41087636, "Neutral": 0.58535117, "Negative": 0.00380252, "Sentiment": "neutral", "RequestId": "c5a4d1c6-61ab-4df5-8eb5-a51aa6194902"}
{"Positive": 0.00056465, "Neutral": 0.99927229, "Negative": 0.00019305, "Sentiment": "neutral", "RequestId": "8cb43c71-c8b9-4de5-a3e0-6d30089807a8"}
{"Positive": 0.89222121, "Neutral": 0.07262803, "Negative": 0.03518075, "Sentiment": "positive", "RequestId": "f23d5eed-dbcc-4b8e-a129-328c1af8d5eb"}
{"Positive": 0.76394737, "Neutral": 0.16122827, "Negative": 0.07485435, "Sentiment": "positive", "RequestId": "71dc8408-3c89-46ec-8e36-85c9e8d6c18e"}
{"Positive": 0.68926394, "Neutral": 0.23371576, "Negative": 0.07705032, "Sentiment": "positive", "RequestId": "d1791d1c-6e1f-4dac-83bd-535ec9c91468"}
{"Positive": 0.84632283, "Neutral": 0.14121947, "Negative": 0.01248766, "Sentiment": "positive", "RequestId": "c219cefd-5084-40f1-b125-2b49ba8d5763"}
{"Positive": 0.58824259, "Neutral": 0.39077684, "Negative": 0.02101055, "Sentiment": "positive", "RequestId": "f6d68156-25df-4e1d-a6fb-71ae82f5c92c"}
{"Positive": 0.70655686, "Neutral": 0.29253936, "Negative": 0.00093376, "Sentiment": "positive", "RequestId": "7ec6477a-97dc-4f99-8d7b-ef03c6e7fedd"}
{"Positive": 0.84208846, "Neutral": 0.08514191, "Negative": 0.07279965, "Sentiment": "positive", "RequestId": "8d663b23-174d-47a6-bcda-2c0440af0983"}
{"Positive": 0.00139269, "Neutral": 0.18047588, "Negative": 0.81816143, "Sentiment": "negative", "RequestId": "3e167f1c-2c63-4abb-bcf5-a5dbd693ecf3"}
{"Positive": 0.00056465, "Neutral": 0.99927229, "Negative": 0.00019305, "Sentiment": "neutral", "RequestId": "6ba86200-2e6a-4699-a12d-65426cdb3bc8"}
{"Positive": 0.20498133, "Neutral": 0.76580822, "Negative": 0.02924048, "Sentiment": "neutral", "RequestId": "e07d3efa-8dcb-45d9-b9b5-4db76ae14059"}
{"Positive": 0.00310454, "Neutral": 0.02119303, "Negative": 0.97573239, "Sentiment": "negative", "RequestId": "ca19fc11-72c7-49e2-8239-4cc2ffc57f47"}
{"Positive": 0.01681216, "Neutral": 0.83704138, "Negative": 0.14617646, "Sentiment": "neutral", "RequestId": "725f45c7-efa6-4efa-bee7-24495cc966b4"}
{"Positive": 0.64517581, "Neutral": 0.3415575, "Negative": 0.01329674, "Sentiment": "positive", "RequestId": "fc402a73-ac7c-4c39-8b49-c58863e7934f"}
{"Positive": 0.89119941, "Neutral": 0.10825511, "Negative": 0.00057554, "Sentiment": "positive", "RequestId": "91dcccb2-26c0-4fb4-ba51-3541621c1159"}

{"Positive": 0.96766782, "Neutral": 0.03028577, "Negative": 0.00207647, "Sentiment": "positive", "RequestId": "ceece944-3256-4f94-8bfa-eb758a4d7870"}
{"Positive": 0.84769249, "Neutral": 0.14417996, "Negative": 0.00815763, "Sentiment": "positive", "RequestId": "267ea84d-d987-47ee-b34b-e9ab1b4c9c8a"}
{"Positive": 0.28416103, "Neutral": 0.52383178, "Negative": 0.19203722, "Sentiment": "neutral", "RequestId": "f505ccdc-4f0d-4bb6-8e73-d557289bfbfa"}
{"Positive": 0.99308151, "Neutral": 0.00673343, "Negative": 0.00021506, "Sentiment": "positive", "RequestId": "6fe0bbd4-90e1-412a-84c6-adcc4133b186"}
{"Positive": 0.49307352, "Neutral": 0.36067417, "Negative": 0.14628237, "Sentiment": "positive", "RequestId": "c9c464a6-62dd-4c77-acb9-1b1765003cc0"}
{"Positive": 0.00056465, "Neutral": 0.99927229, "Negative": 0.00019305, "Sentiment": "neutral", "RequestId": "5d184e22-01ab-45f1-ba00-bf234d1a6179"}
{"Positive": 0.92419094, "Neutral": 0.06321245, "Negative": 0.01262662, "Sentiment": "positive", "RequestId": "3b5afb8d-66ae-4f04-b38f-c628b48fbafc"}
{"Positive": 0.95655578, "Neutral": 0.04337016, "Negative": 0.00010409, "Sentiment": "positive", "RequestId": "814f3e44-fdda-44c2-9eb6-58ddd6dcbc18"}
{"Positive": 0.89298522, "Neutral": 0.10683242, "Negative": 0.00021233, "Sentiment": "positive", "RequestId": "d86d9e02-c0b6-485c-a041-bf915d689f30"}
{"Positive": 0.86106813, "Neutral": 0.08342142, "Negative": 0.05554054, "Sentiment": "positive", "RequestId": "fb3ac411-f4c4-4d62-bded-dbe954a075b6"}
{"Positive": 0.17856565, "Neutral": 0.75575024, "Negative": 0.06571408, "Sentiment": "neutral", "RequestId": "8cc6114a-5797-4805-a6e7-75f290cb4844"}
{"Positive": 0.85866028, "Neutral": 0.10816669, "Negative": 0.03320296, "Sentiment": "positive", "RequestId": "62c0db6f-5219-4426-a86e-1af9515244a6"}
{"Positive": 0.97094935, "Neutral": 0.02887304, "Negative": 0.00020763, "Sentiment": "positive", "RequestId": "1d0d7a84-ac74-48d8-9a65-548dd031e5b2"}
{"Positive": 0.82575393, "Neutral": 0.10079659, "Negative": 0.07347944, "Sentiment": "positive", "RequestId": "be75cf38-ef9f-4017-983d-e74465d25c5b"}
{"Positive": 0.0005968, "Neutral": 0.00017441, "Negative": 0.99925882, "Sentiment": "negative", "RequestId": "65a66697-bb05-46af-9b36-678132bbee94"}
{"Positive": 0.97352159, "Neutral": 0.01061747, "Negative": 0.01589094, "Sentiment": "positive", "RequestId": "75a268cb-2b1c-4d5f-a9e0-e0c9f7420b94"}
{"Positive": 0.03288443, "Neutral": 0.95086348, "Negative": 0.01628217, "Sentiment": "neutral", "RequestId": "46e9198e-990f-449d-a301-ad73bbec4cc3"}
{"Positive": 0.88526464, "Neutral": 0.1127494, "Negative": 0.00201604, "Sentiment": "positive", "RequestId": "a7d512d0-8e81-4a4f-b1cf-93621127caa4"}
{"Positive": 0.00956566, "Neutral": 0.10010672, "Negative": 0.89035755, "Sentiment": "negative", "RequestId": "adf76dab-4df7-4b5b-8f53-2a44c6713ea2"}
{"Positive": 0.09406865, "Neutral": 0.43680051, "Negative": 0.4691608, "Sentiment": "negative", "RequestId": "7cb26897-b83a-4a69-afea-37474a0e2cfa"}
{"Positive": 0.570274, "Neutral": 0.38438591, "Negative": 0.04537008, "Sentiment": "positive", "RequestId": "84ceff10-e483-49c7-ab48-60656af0001f"}
{"Positive": 0.0824081, "Neutral": 0.75883597, "Negative": 0.15878589, "Sentiment": "neutral", "RequestId": "d70aec6a-b2b2-4786-b596-42bc16968e2b"}
{"Positive": 0.01926023, "Neutral": 0.97221404, "Negative": 0.00855577, "Sentiment": "neutral", "RequestId": "38752a22-5322-4cf9-bf00-dc9f629d42f6"}
{"Positive": 1.398e-05, "Neutral": 0.00057836, "Negative": 0.99943775, "Sentiment": "negative", "RequestId": "2a65fe7a-e9b9-47f8-addc-55e142dcce8d"}
{"Positive": 1.00000644, "Neutral": 1.041e-05, "Negative": 1.322e-05, "Sentiment": "positive", "RequestId": "891d6e6a-4b57-4f39-bb58-d6fd927e23a8"}
{"Positive": 0.99996138, "Neutral": 2.617e-05, "Negative": 4.239e-05, "Sentiment": "positive", "RequestId": "9c3ce8d1-2a79-40e8-941f-65f54856bb48"}
{"Positive": 0.86637878, "Neutral": 0.1191151, "Negative": 0.01453613, "Sentiment": "positive", "RequestId": "ec2defed-c9cc-47ec-bb00-f057cefcab64"}
{"Positive": 0.2807022, "Neutral": 0.64672178, "Negative": 0.07260608, "Sentiment": "neutral", "RequestId": "06fc1da2-929d-40d9-924c-074a5020cafe"}
{"Positive": 0.44397354, "Neutral": 0.45691577, "Negative": 0.0991407, "Sentiment": "neutral", "RequestId": "8a319494-16df-4b0e-808b-51e254b08e7f"}
{"Positive": 0.51814002, "Neutral": 0.04192103, "Negative": 0.43996894, "Sentiment": "positive", "RequestId": "bbfe49cc-aca6-4abd-91d0-9e84e8403a3e"}
{"Positive": 0.75043213, "Neutral": 0.21944426, "Negative": 0.03015358, "Sentiment": "positive", "RequestId": "7dec86be-396e-4fb0-ac04-389cb253d685"}
{"Positive": 0.47778085, "Neutral": 0.37697241, "Negative": 0.14527678, "Sentiment": "positive", "RequestId": "3cd7236b-2b19-4c1f-ba76-f4167e06f8d0"}
{"Positive": 0.00056465, "Neutral": 0.99927229, "Negative": 0.00019305, "Sentiment": "neutral", "RequestId": "b530fcb9-77e5-4357-a172-3cbb9247d780"}
{"Positive": 0.9999727, "Neutral": 1.125e-05, "Negative": 4.601e-05, "Sentiment": "positive", "RequestId": "e4b09183-e761-4b9f-b473-22d8f920f60b"}
{"Positive": 0.01191098, "Neutral": 0.98794359, "Negative": 0.00017553, "Sentiment": "neutral", "RequestId": "49e76bb8-15e7-41c0-9733-3124ab52b726"}
{"Positive": 0.67965525, "Neutral": 0.09039099, "Negative": 0.22998373, "Sentiment": "positive", "RequestId": "55824f03-06b5-4fab-a60c-fa8bb602bb7d"}
{"Positive": 0.00462735, "Neutral": 0.03681492, "Negative": 0.95858777, "Sentiment": "negative", "RequestId": "57d94a7d-a222-4abb-9e45-b9957e5facea"}
{"Positive": 0.53385502, "Neutral": 0.14519292, "Negative": 0.3209821, "Sentiment": "positive", "RequestId": "6015eab9-4322-4f71-a393-5d1d8773d850"}
{"Positive": 0.91658151, "Neutral": 0.03171093, "Negative": 0.0517376, "Sentiment": "positive", "RequestId": "b6b101a7-6d96-46e7-9293-5c305e4941d2"}
{"Positive": 0.9982639, "Neutral": 0.00166658, "Negative": 9.947e-05, "Sentiment": "positive", "RequestId": "0386615a-2161-4dd9-ad07-afe622d1b517"}
{"Positive": 0.78024662, "Neutral": 0.15202253, "Negative": 0.06776088, "Sentiment": "positive", "RequestId": "665eff79-08d2-4d24-bfa1-82012900d013"}
{"Positive": 0.14570805, "Neutral": 0.82033789, "Negative": 0.03398406, "Sentiment": "neutral", "RequestId": "42af5591-1973-491b-b14e-ae98587b227f"}
{"Positive": 0.131997, "Neutral": 0.7953763, "Negative": 0.07265669, "Sentiment": "neutral", "RequestId": "afa95eaf-0e4a-4042-9bc7-9843d760fc5c"}
{"Positive": 0.00056465, "Neutral": 0.99927229, "Negative": 0.00019305, "Sentiment": "neutral", "RequestId": "e8d1aace-ff88-408b-a304-a44223affdb8"}
{"Positive": 0.0173729, "Neutral": 0.29073763, "Negative": 0.69191951, "Sentiment": "negative", "RequestId": "244e8580-7d00-4e26-83ad-2443ab9fb4fe"}
{"Positive": 0.67672372, "Neutral": 0.21930833, "Negative": 0.10399795, "Sentiment": "positive", "RequestId": "5b32b60e-1754-47df-8b6e-808b40f93d0b"}
{"Positive": 0.03883746, "Neutral": 0.21484597, "Negative": 0.74634659, "Sentiment": "negative", "RequestId": "e4c05c92-da54-4dce-b2a8-b7e9216fc499"}
{"Positive": 0.01676511, "Neutral": 0.70523989, "Negative": 0.27802497, "Sentiment": "neutral", "RequestId": "f9b87ee8-f116-4c56-8285-85c9abe7121f"}
{"Positive": 0.38940737, "Neutral": 0.08249447, "Negative": 0.52812821, "Sentiment": "negative", "RequestId": "0be40af8-d73a-430c-83c0-d4f60d156f93"}
{"Positive": 0.98050535, "Neutral": 0.01728483, "Negative": 0.00223997, "Sentiment": "positive", "RequestId": "fa9276b2-e9bd-407d-8c7c-056617cf755b"}
{"Positive": 0.00056465, "Neutral": 0.99927229, "Negative": 0.00019305, "Sentiment": "neutral", "RequestId": "948bc02b-6bfd-4a15-b9d8-8ab900a17570"}
{"Positive": 0.7878992, "Neutral": 0.2119178, "Negative": 0.00021306, "Sentiment": "positive", "RequestId": "a8390330-cfe9-4779-9195-c1baa595c1ef"}
{"Positive": 0.57938236, "Neutral": 0.3635923, "Negative": 0.05705536, "Sentiment": "positive", "RequestId": "1ea43d28-25ca-4781-997a-ff79fa584afd"}
{"Positive": 0.59410781, "Neutral": 0.00155029, "Negative": 0.40437186, "Sentiment": "positive", "RequestId": "1e8ce8d0-af28-4cd4-9a20-0fa980c322bf"}
{"Positive": 0.83472103, "Neutral": 0.16526812, "Negative": 4.083e-05, "Sentiment": "positive", "RequestId": "6a664cbb-845a-474f-bd5a-04b795d524b7"}
{"Positive": 0.07566252, "Neutral": 0.19974262, "Negative": 0.72462493, "Sentiment": "negative", "RequestId": "06a34ecd-14f1-409b-9658-f8f7e416cf15"}

{"Positive": 0.86368775, "Neutral": 0.13313626, "Negative": 0.00320601, "Sentiment": "positive", "RequestId": "a1719c4e-8bc2-4395-8ca5-cf6df0d9a828"}
{"Positive": 0.86482394, "Neutral": 0.10503405, "Negative": 0.03017196, "Sentiment": "positive", "RequestId": "686906c5-5130-4134-8b66-9f4676e1d589"}
{"Positive": 0.71974671, "Neutral": 0.1987047, "Negative": 0.08157859, "Sentiment": "positive", "RequestId": "7df66f58-2bec-4de4-9cd6-c2c44a231735"}
{"Positive": 0.46175388, "Neutral": 0.04324037, "Negative": 0.49503565, "Sentiment": "negative", "RequestId": "770bb8fa-8783-4445-9ede-091e796c478f"}
{"Positive": 0.00056465, "Neutral": 0.99927229, "Negative": 0.00019305, "Sentiment": "neutral", "RequestId": "c4cb4cb7-c8fc-4482-8eb5-db641d21569f"}
{"Positive": 0.62945634, "Neutral": 0.36240852, "Negative": 0.00816512, "Sentiment": "positive", "RequestId": "6b9baf6e-4124-4dc6-90a4-48cc6b52dcdf"}
{"Positive": 0.02983843, "Neutral": 0.96194774, "Negative": 0.00824378, "Sentiment": "neutral", "RequestId": "b779c73c-e269-4357-b888-8938cebb6228"}
{"Positive": 0.96739453, "Neutral": 0.02467834, "Negative": 0.00795715, "Sentiment": "positive", "RequestId": "be5443e1-ac53-4f58-bc73-511db0bf4253"}
{"Positive": 0.29537037, "Neutral": 0.49188873, "Negative": 0.21277094, "Sentiment": "neutral", "RequestId": "08bf28c7-e6d5-420c-97b6-a43302f6df78"}
{"Positive": 0.17268816, "Neutral": 0.68114686, "Negative": 0.14619505, "Sentiment": "neutral", "RequestId": "f0135898-3061-4e81-94d6-1f54a2abba4d"}
{"Positive": 0.96869785, "Neutral": 0.02498726, "Negative": 0.00634492, "Sentiment": "positive", "RequestId": "25e76627-43d3-4bd8-ad1f-c56dac80f52f"}
{"Positive": 0.00740352, "Neutral": 0.02028358, "Negative": 0.97234297, "Sentiment": "negative", "RequestId": "0fd0bd1f-624c-4161-b299-6cd074d2fe79"}
{"Positive": 0.79526222, "Neutral": 0.18687141, "Negative": 0.01789636, "Sentiment": "positive", "RequestId": "f7fde4a9-eeb6-4bcf-afd8-1fb5e402799d"}
{"Positive": 0.02458218, "Neutral": 0.88737291, "Negative": 0.08807493, "Sentiment": "neutral", "RequestId": "99ee8b93-1ab1-4bfd-87a3-219889bc3fff"}
{"Positive": 0.33266479, "Neutral": 0.28686324, "Negative": 0.38050202, "Sentiment": "negative", "RequestId": "884db8cd-7eb6-407a-a7f6-b0bd63a25da0"}
{"Positive": 0.02543624, "Neutral": 0.82840854, "Negative": 0.14618523, "Sentiment": "neutral", "RequestId": "cfea4d87-d3b6-463e-8813-ebaaf67c137e"}
{"Positive": 7.511e-05, "Neutral": 0.0526027, "Negative": 0.94735211, "Sentiment": "negative", "RequestId": "c0f4dbd1-188e-46cb-aadf-e25dac498d1a"}
{"Positive": 0.65739608, "Neutral": 0.07396933, "Negative": 0.26866451, "Sentiment": "positive", "RequestId": "3ae1022d-5a91-4866-b10e-f746dffea11c"}
{"Positive": 0.71473819, "Neutral": 0.04365029, "Negative": 0.24164154, "Sentiment": "positive", "RequestId": "3fc5c9f8-5607-48aa-b5ab-bb607c952162"}
{"Positive": 0.29457492, "Neutral": 0.70327669, "Negative": 0.00217844, "Sentiment": "neutral", "RequestId": "b8f22b3c-ce79-4453-93dd-1603b669a3b6"}
{"Positive": 0.13247949, "Neutral": 0.75250775, "Negative": 0.11504275, "Sentiment": "neutral", "RequestId": "98aab680-5237-4933-858e-0b5f1a0f4b68"}
{"Positive": 0.77591389, "Neutral": 0.1917408, "Negative": 0.03237539, "Sentiment": "positive", "RequestId": "f0fdbb3f-4675-44a7-8df9-943dc09b882f"}
{"Positive": 0.02983843, "Neutral": 0.96194774, "Negative": 0.00824378, "Sentiment": "neutral", "RequestId": "90526381-67b0-4a3b-90a5-03cbb5726e15"}
{"Positive": 0.02083238, "Neutral": 0.97747481, "Negative": 0.00172285, "Sentiment": "neutral", "RequestId": "9abc8421-678d-4756-b387-55b74985bf84"}
{"Positive": 0.04023753, "Neutral": 0.32943043, "Negative": 0.63036209, "Sentiment": "negative", "RequestId": "ab94039d-c0b9-49b6-8450-494c6e86837f"}
{"Positive": 0.00056465, "Neutral": 0.99927229, "Negative": 0.00019305, "Sentiment": "neutral", "RequestId": "fc23822f-e866-4245-9530-646ea9c5b082"}
{"Positive": 0.85786521, "Neutral": 0.11703064, "Negative": 0.02513418, "Sentiment": "positive", "RequestId": "e0fe7afa-c8a8-43e2-bdf7-3f8a9e57d2d2"}
{"Positive": 0.01473789, "Neutral": 0.97478598, "Negative": 0.01050619, "Sentiment": "neutral", "RequestId": "fadd3d4e-e572-4a93-b0d4-8598047c8e03"}
{"Positive": 0.56825119, "Neutral": 0.41802567, "Negative": 0.01375316, "Sentiment": "positive", "RequestId": "84a40068-0aee-460f-9588-9ba95b2003cf"}
{"Positive": 0.32614422, "Neutral": 0.40768433, "Negative": 0.26620138, "Sentiment": "neutral", "RequestId": "33bf421c-dad8-4dac-8030-2d023701f8ec"}
{"Positive": 0.31321269, "Neutral": 0.41317341, "Negative": 0.27364391, "Sentiment": "neutral", "RequestId": "fed36648-7a9d-4892-b55a-ae591b795d65"}
{"Positive": 0.86391705, "Neutral": 0.06588055, "Negative": 0.07023245, "Sentiment": "positive", "RequestId": "fc5b68c0-7792-43e3-9686-45d81f27afb4"}
{"Positive": 0.72578311, "Neutral": 0.09102781, "Negative": 0.18321915, "Sentiment": "positive", "RequestId": "88ef03c9-4cd3-4c0b-be8a-51b392e35426"}
{"Positive": 0.02083238, "Neutral": 0.97747481, "Negative": 0.00172285, "Sentiment": "neutral", "RequestId": "77b614e9-f644-4ceb-8a45-8cde60ae0d7d"}
{"Positive": 0.99988699, "Neutral": 3.176e-05, "Negative": 0.00011125, "Sentiment": "positive", "RequestId": "6d04bbbc-9733-4740-b5f0-2381d8a98caa"}

KeyboardInterrupt:

In [ ]:
len(list_median_sentiment)

In [ ]:
# 将list_median_sentimen进行拆分
# dic_list_median_sentiment = list_median_sentiment[1]
def string_dic(string1):
    string1 = string1.replace('{','')
    string1 = string1.replace('}','')
    string1 = string1.replace('"','')
    dic_item_median_sentiment = dict(x.split(":") for x in string1.split(","))
    return dic_item_median_sentiment
#

In [ ]:
# string_dic(list_median_sentiment)
# list_median_sentiment1 = list(map(string_dic,list_median_sentiment))
# list_median_sentiment1
list_median_new = []

# {"Positive": 0.36061561, "Neutral": 0.53547966, "Negative": 0.10393469, "Sentiment": "neutral", "RequestId": "dbc96b0e-a81d-4b5b-89d6-f41483e567b7"}


list_median_Positive = []
list_median_Neutral = []
list_median_Negative = []
list_median_Sentiment = []
list_median_RequestId = []

for item1 in list_median_sentiment:
    list_values = []
    item_median = string_dic(item1)
    list_values = list(item_median.values())
    list_median_Positive.append(float(list_values[0])*100)
    list_median_Neutral.append(float(list_values[1])*100)
    list_median_Negative.append(float(list_values[2])*100)
    list_median_Sentiment.append(list_values[3])
    list_median_RequestId.append(list_values[4])
    
    # list_median_new.append(item_median)
print(len(list_median_Positive))
print(len(list_median_Neutral))
print(len(list_median_Negative))
print(len(list_median_Sentiment))
print(len(list_median_RequestId))

In [ ]:
# new_list_comment_detail = data_new['comment_detail']
# list_median_Positive = []
# list_median_Neutral = []
# list_median_Negative = []
# list_median_Sentiment = []
# list_median_RequestId = []

data_new1 ['Positive'] = list_median_Positive
data_new1 ['Neutral'] = list_median_Neutral
data_new1 ['Negative'] = list_median_Negative
data_new1 ['Sentiment'] = list_median_Sentiment
data_new1 ['RequestId'] = list_median_RequestId
data_new1

In [ ]:
# 将data_new1和要打开的data_new2进行合并
data_new1.to_csv('E:\\论文\\第二篇论文\\medianResult_commentLevel_between0_200_0223.csv',encoding = 'utf-8')

In [ ]:
# 打开data_new1
data_new11 = pd.read_csv('E:\\论文\\第二篇论文\\medianResult_commentLevel_between0_200_0223.csv',encoding = 'utf-8')
data_new11['id'] = list(range(len(data_new2),len(data_new2)+len(data_new11)))
data_new111 = data_new11[['id','comment_day','scence_name','comment_id','comment_detail','comment_len','Positive','Neutral','Negative','Sentiment','RequestId']]
data_new111

In [ ]:
data_new2 = pd.read_csv('E:\\论文\\第二篇论文\\medianResult_commentLevel_more200_0223.csv',encoding = 'utf-8')
data_new2['id'] = list(range(len(data_new2)))
data_new2

In [ ]:
data_new22 = data_new2[['id','comment_day','scence_name','comment_id','comment_len','Positive','Neutral','Negative','Sentiment','RequestId']]
data_new22

In [ ]:
# data_new1['id'] = list(range(len(data_new2),len(data_new2)+len(data_new1)))
# data_new12 = data_new1[['id','comment_day','scence_name','comment_id','comment_len','Positive','Neutral','Negative','Sentiment','RequestId']]
# data_new12

In [ ]:
type(data_new11)

In [ ]:
data_new11.update(data_new22)

## 对评论字数大于200的评论进行情感打分

In [ ]:
data_new_over200 = data_new[data_new['comment_len']>=200] 
data_new_over200

In [ ]:
import math
# 针对大于200字的文本，我们可以将文本分割，每个文本200个字即可
# # 选取前10个评论来测试
# data_new_more_200_1 = data_new_more_200[:9]

# 选取全部评论来测试
data_new_more_200_1 = data_new_over200

new2_data_over200 = []

list_texts_all = []
list_data_new_more200 = data_new_more_200_1['comment_detail']
for text in list_data_new_more200:
#     print(text)
#     print('\n')

    list_context_200 = []
    pages = math.ceil(len(text)/200)
    for num in range(pages):
        list_context_200.append(text[200*(num):200*(num+1)])
        list_texts_all.append(text[200*(num):200*(num+1)])
    new2_data_over200.append(list_context_200)
print(len(new2_data_over200))
print(len(list_texts_all))
# new2_data_over200 list1中套了list_texts,每个list_texts中为分段的评论

In [ ]:
# 这里对list_texts_all进行情感打分，过程同data_new1的构成一样，此处省略

In [ ]:
data_new22['comment_detail'] = list_texts_all

## 将大于200和(0,200)的评论进行合并

In [ ]:
df3 = pd.concat([data_new111,data_new22],axis=0)
df3

## 罗列出新数据的情感得分sentiment_score

In [ ]:
def most_likey_sentiment(num1,num2,num3):
    sentiment_likely = max(num1,num2,num3)
    return sentiment_likey
# print(data_median_test)
list_sentiment_likely = []
for i in range(len(df3)):
    max_sentiment = max(df3['Positive'].iloc[i],df3['Neutral'].iloc[i],df3['Negative'].iloc[i])
    list_sentiment_likely.append(max_sentiment)
# list_sentiment_likely

In [ ]:
df3['sentiment_score'] = list_sentiment_likely

In [ ]:
# comment_day	comment_id	scence_name	comment_detail	Positive	Neutral	Negative	Sentiment	RequestId	sentiment_score
df33 = df3[['comment_day','comment_id','scence_name','comment_detail','Positive','Neutral','Negative','Sentiment','RequestId','sentiment_score']]

In [ ]:
# 打开202212月前的完整数据
df1 = pd.read_csv('D:\\linxi\\All_comments_sentiment.csv',encoding = 'utf-8')
df1.head()

In [ ]:
df2 = df1[['comment_day','comment_id','scence_name','comment_detail','Positive','Neutral','Negative','Sentiment','RequestId','sentiment_score']]
df2

In [ ]:
df4 = pd.concat([df2,df33],axis = 0)
df4

In [ ]:
def most_likey_sentiment(num1,num2,num3):
    sentiment_likely = max(num1,num2,num3)
    return sentiment_likey
# print(data_median_test)
list_sentiment_likely = []
for i in range(len(df4)):
    max_sentiment = max(df4['Positive'].iloc[i],df4['Neutral'].iloc[i],df4['Negative'].iloc[i])
    list_sentiment_likely.append(max_sentiment)
# list_sentiment_likely
df4

In [ ]:
df4.to_csv('E:\\论文\\第二篇论文\\评论层面数据集合.csv',encoding = 'utf-8-sig')

## 将各地每天都数据进行整合
## 我们可以不将原始的数据进行，可以就在评论层面使用机器学习模型，对情感值进行预测。

In [18]:
data_weather

,scence_id,scence_city,scence_date,low_temperature,high_temperature,weather_type,wind,weather1,weather2
0,1352,天津,20190601,21,31,阵雨/阴,东南风1-2级/东南风1-2级,阵雨,阴
1,1353,天津,20190602,22,34,阴/雷阵雨,西南风3-4级/西南风3-4级,阴,雷阵雨
2,1354,天津,20190603,21,32,多云/阴,东南风3-4级/东南风3-4级,多云,阴
3,1355,天津,20190604,21,27,雷阵雨/雷阵雨,东风4-5级/东风4-5级,雷阵雨,雷阵雨
4,1356,天津,20190605,19,27,阴/中雨,东北风3-4级/东北风3-4级,阴,中雨
...,...,...,...,...,...,...,...,...,...
231435,251002,呼伦贝尔,20221227,-27,-21,多云/小雪,西北风1-2级/西北风1-2级,多云,小雪
231436,251003,呼伦贝尔,20221228,-32,-22,小雪/晴,西风3-4级/西风3-4级,小雪,晴
231437,251004,呼伦贝尔,20221229,-30,-21,晴/晴,西风3-4级/西风1-2级,晴,晴
231438,251005,呼伦贝尔,20221230,-26,-16,晴/晴,西南风3-4级/西风3-4级,晴,晴
231439,251006,呼伦贝尔,20221231,-30,-19,晴/晴,西风3-4级/西风3-4级,晴,晴

In [19]:
# 将天气的数据进行清洗

import pymysql
import pandas as pd
#连接数据库
conn=pymysql.connect(host = '127.0.0.1' # 连接名称，默认127.0.0.1
,user = 'root' # 用户名
,passwd='123456' # 密码
,port= 3306 # 端口，默认为3306
,db='weibo0223' # 数据库的名字
,charset='utf8' # 字符编码
)
cur = conn.cursor() # 生成游标对象
sql="select * from `weather`  " # SQL语句
cur.execute(sql) # 执行SQL语句
data = cur.fetchall() # 通过fetchall方法获得数据
for i in data[:20]: # 打印输出前3条数据
    print(i)
# cur.close() # 关闭游标
# conn.close() # 关闭连接

(1352, '天津', '20190601', 21, 31, '阵雨/阴', '东南风1-2级/东南风1-2级')
(1353, '天津', '20190602', 22, 34, '阴/雷阵雨', '西南风3-4级/西南风3-4级')
(1354, '天津', '20190603', 21, 32, '多云/阴', '东南风3-4级/东南风3-4级')
(1355, '天津', '20190604', 21, 27, '雷阵雨/雷阵雨', '东风4-5级/东风4-5级')
(1356, '天津', '20190605', 19, 27, '阴/中雨', '东北风3-4级/东北风3-4级')
(1357, '天津', '20190606', 18, 24, '小雨/多云', '东北风3-4级/东北风3-4级')
(1358, '天津', '20190607', 22, 33, '多云/雷阵雨', '西南风3-4级/西南风3-4级')
(1359, '天津', '20190608', 21, 33, '阴/阴', '南风1-2级/南风1-2级')
(1360, '天津', '20190609', 20, 31, '晴/晴', '北风3-4级/北风3-4级')
(1361, '天津', '20190610', 21, 32, '晴/晴', '东南风3-4级/东南风3-4级')
(1362, '天津', '20190611', 23, 30, '晴/多云', '东南风3-4级/东南风3-4级')
(1363, '天津', '20190612', 22, 34, '多云/阴', '西南风3-4级/西南风3-4级')
(1364, '天津', '20190613', 21, 30, '雷阵雨/多云', '北风3-4级/北风3-4级')
(1365, '天津', '20190614', 22, 34, '晴/晴', '东北风1-2级/东北风1-2级')
(1366, '天津', '20190615', 21, 30, '多云/雷阵雨', '东南风3-4级/东南风3-4级')
(1367, '天津', '20190616', 20, 24, '阵雨/阴', '东风3-4级/东风3-4级')
(1368, '天津', '20190617', 22, 30, '多云/多云', '东风1-2级/东风1-2级')
(1369, '天津', '20190618', 21, 34, '阴/阴', '东南风1-2级/东南风1-2级')
(1370, '天津', '20190619', 23, 30, '阵雨/阴', '东南风3-4级/东南风3-4级')
(1371, '天津', '20190620', 24, 33, '多云/多云', '东南风1-2级/东南风1-2级')

## 1. 将df4中的scence_city 与 scence中的old_city聚合
## 2. 通过sence中的new_city和weather中的city聚合
## 3. 设置holiday
## 4. 设置period1, period2等
## 5. 设置month1-month12

In [20]:
# 将df4中的scence_city 与 scence中的old_city聚合
import pandas as pd
df4 = pd.read_csv('E:\\论文\\第二篇论文\\截止到2023年2月数据汇总\\评论层面数据集合.csv',encoding = 'utf-8-sig')
df4

,comment_id,comment_time,scence_name,comment_detail,Positive,Neutral,Negative,Sentiment,RequestId,sentiment_score
0,1451,2022-11-25,圆明园,明天就要降温了今天风好大,27.513403,51.240921,21.248679,neutral,c4e80585-89fa-4c15-bada-f23957e8ec65,51.240921
1,1452,2022-11-25,圆明园,这样能封一辈子吗病毒没死几个人防疫倒是快把人折磨死了,2.416031,8.446255,89.140707,negative,30495bee-4108-4461-b40f-b42f98ff7dc8,89.140707
2,1453,2022-11-25,圆明园,圆明园被烧十二年后长春园西洋楼花园门残影摄于公元1873同治十二年,43.924150,54.498631,1.580220,neutral,b0798e05-fea4-4dfa-94cf-49f3cc3657e8,54.498631
3,1454,2022-11-25,圆明园,分享图片,0.056465,99.927229,0.019305,neutral,ae886551-4939-4b56-8ec6-3d40e4d119e1,99.927229
4,1455,2022-11-25,圆明园,吃完饭坐上坐骑真舒服呀,99.985266,0.016083,0.001650,positive,75417462-afad-444c-8983-f21f633fe577,99.985266
...,...,...,...,...,...,...,...,...,...,...
335760,256224,2021-09-21,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,DAY3 可可托海镇-可可托海风景区（额尔齐斯大峡谷），徒步10公里，聆听额尔齐斯河的欢歌，...,71.821064,20.475243,7.706693,positive,43d591a4-b520-4113-b870-eeb2e9c1d9df,71.821064
335761,256224,2021-09-21,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,的树林，额尔齐斯河时而咆哮时而蜿蜒，一路向北，奔向北冰洋。透明的黄，深沉的黄在河边和峡谷弥漫...,63.880837,22.737600,13.384573,positive,ee7e3435-1218-484c-842a-ad59e6330be9,63.880837
335762,256224,2021-09-21,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,票价10元，整个景区用时约7小时左右。最佳观赏期每年9.20-10.7之间。,80.376095,14.673571,4.953333,positive,e59dcfd6-414d-4395-8900-2315af404811,80.376095
335763,256317,2019-07-19,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,当第一缕阳光崩出天际，可可托海的生物们又迎来了崭新的一天。谁是早起冠军呢？是漫步山野之间的牛...,29.673469,61.576158,8.753374,neutral,48b14b35-91b1-40f0-9ef1-23768bc447ab,61.576158
335764,256317,2019-07-19,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,见他一眼就会迷恋上那双透彻的眼睛，直射人心，重击灵魂。,21.208419,74.240619,4.553967,neutral,8c62b25b-ea62-4ddc-9047-f3cbf478fd63,74.240619

In [21]:
# 将scence的数据进行清洗

import pymysql
import pandas as pd
#连接数据库
conn=pymysql.connect(host = '127.0.0.1' # 连接名称，默认127.0.0.1
,user = 'root' # 用户名
,passwd='123456' # 密码
,port= 3306 # 端口，默认为3306
,db='weibo0223' # 数据库的名字
,charset='utf8' # 字符编码
)
cur = conn.cursor() # 生成游标对象
sql="select * from `scene`  " # SQL语句
cur.execute(sql) # 执行SQL语句
data_scene = cur.fetchall() # 通过fetchall方法获得数据
for i in data_scene[:20]: # 打印输出前3条数据
    print(i)
# cur.close() # 关闭游标
# conn.close() # 关闭连接

(1, '1001', '圆明园', '北京', 'https://weibo.com/p/100101B2094654D66EA3FE439C')
(2, '1002', '奥林匹克公园', '北京', 'http://weibo.com/p/100101B2094251D064A6F9439D')
(3, '1003', '恭王府景区', '北京', 'https://weibo.com/p/100101B2094757D06EAAFD489E')
(4, '1004', '北京市明十三陵景区', '北京', 'https://weibo.com/p/100101B2094654D365A4FC4392')
(5, '1004', '北京市明十三陵景区', '北京', 'https://weibo.com/p/100101B2094450DA68A4F54199')
(6, '1004', '北京市明十三陵景区', '北京', 'http://weibo.com/p/100101B2094757D66DA7F4479B')
(7, '1005', '北京八达岭－慕田峪长城旅游区', '北京', 'http://weibo.com/p/100101B2094757D56FA3F5439A')
(8, '1006', '颐和园', '北京', 'https://weibo.com/p/100101B2094654D26FA1F5499D')
(9, '1007', '天坛公园', '北京', 'https://weibo.com/p/100101B2094757D06FA5F84492')
(10, '1008', '故宫博物院', '北京', 'https://weibo.com/p/100101B2094654D66CA4FB4098')
(11, '1009', '盘山风景名胜区', '天津', 'https://weibo.com/p/100101B2094253D268A7FF419A')
(12, '1010', '天津古文化街旅游区（津门故里）', '天津', 'https://weibo.com/p/100101B2094757D06FA1FA479E')
(13, '1011', '河北省保定市清西陵景区', '保定市', 'http://weibo.com/p/100101B2094757D56FA4FB4398')
(14, '1012', '秦皇岛市山海关景区', '秦皇岛市', 'https://weibo.com/p/100101B2094757D068A3F44999')
(15, '1013', '邯郸市广府古城景区', '邯郸市', 'http://weibo.com/p/100101B2094254D66AA4FE4999')
(16, '1014', '保定市白石山景区', '保定市', 'https://weibo.com/p/100101B2094450D56FA2FD449C')
(17, '1015', '邯郸市娲皇宫景区', '邯郸市', 'http://weibo.com/p/100101B2094757D16BA6FE469D')
(18, '1016', '唐山市清东陵景区', '唐山市', 'https://weibo.com/p/100101B2094757D66CA6F8479F')
(19, '1017', '石家庄市西柏坡景区', '石家庄市', 'http://weibo.com/p/100101B2094656D365A3FE4198')
(20, '1018', '保定市野三坡景区', '保定市', 'https://weibo.com/p/100101B2094656D06FA0FA479D')

In [22]:
# sceneID | scenename    | scenecity | sceneurl

list_scence_id = []
list_scenename = []
list_scenecity = []
list_sceneurl = []

for items in data_scene:
    scence_id = items[1]
    scenename = items[2]
    scenecity = items[3]
    sceneurl = items[4]

#     scence_id = scence_id.strip()
    scenename = scenename.strip()
    scenecity = scenecity.strip()
    sceneurl = sceneurl.strip()

    list_scence_id.append(scence_id)
    list_scenename.append(scenename)
    list_scenecity.append(scenecity)
    list_sceneurl.append(sceneurl)

    

list_scenename

['圆明园',
 '奥林匹克公园',
 '恭王府景区',
 '北京市明十三陵景区',
 '北京市明十三陵景区',
 '北京市明十三陵景区',
 '北京八达岭－慕田峪长城旅游区',
 '颐和园',
 '天坛公园',
 '故宫博物院',
 '盘山风景名胜区',
 '天津古文化街旅游区（津门故里）',
 '河北省保定市清西陵景区',
 '秦皇岛市山海关景区',
 '邯郸市广府古城景区',
 '保定市白石山景区',
 '邯郸市娲皇宫景区',
 '唐山市清东陵景区',
 '石家庄市西柏坡景区',
 '保定市野三坡景区',
 '承德市避暑山庄及周围寺庙景区',
 '保定市安新白洋淀景区',
 '山西省长治市壶关太行山大峡谷八泉峡景区',
 '临汾市洪洞县洪洞大槐树寻根祭祖园旅游景区',
 '忻州市雁门关景区',
 '平遥古城',
 '晋城市皇城相府生态文化旅游区',
 '忻州市五台山风景名胜区',
 '大同市云冈石窟',
 '内蒙古自治区阿拉善盟胡杨林旅游区',
 '赤峰市阿斯哈图石阵旅游区',
 '赤峰市阿斯哈图石阵旅游区',
 '阿尔山·柴河旅游景区',
 '满洲里市中俄边境旅游区',
 '鄂尔多斯市成吉思汗陵旅游区',
 '鄂尔多斯市成吉思汗陵旅游区',
 '辽宁省盘锦市红海滩风景廊道景区',
 '本溪市本溪水洞景区',
 '大连市金石滩景区',
 '大连市大连老虎滩海洋公园·老虎滩极地馆',
 '沈阳市植物园',
 '吉林省通化市高句丽文物古迹旅游景区',
 '吉林省通化市高句丽文物古迹旅游景区',
 '吉林省通化市高句丽文物古迹旅游景区',
 '长春市世界雕塑公园旅游景区',
 '延边朝鲜族自治州敦化市六鼎山文化旅游区',
 '延边朝鲜族自治州敦化市六鼎山文化旅游区',
 '长春市长影世纪城旅游区',
 '长春市净月潭景区',
 '延边朝鲜族自治州安图县长白山景区',
 '长春市伪满皇宫博物院',
 '漠河市北极村旅游区',
 '伊春市汤旺河林海奇石景区',
 '牡丹江市镜泊湖景区',
 '牡丹江市镜泊湖景区',
 '黑河市五大连池景区',
 '哈尔滨市太阳岛景区',
 '上海科技馆',
 '上海东方明珠广播电视塔',
 '上海东方明珠广播电视塔',
 '上海东方明珠广播电视塔',
 '上海野生动物园',
 '江苏省无锡市惠山古镇景区',
 '常州市中国春秋淹城旅游区',
 '连云港市花果山景区',
 '徐州市云龙湖景区',
 '大丰中华麋鹿园景区',
 '大丰中华麋鹿园景区',
 '周恩来故里旅游景区',
 '镇江市句容茅山景区',
 '苏州市沙家浜·虞山尚湖旅游区',
 '常州市天目湖景区',
 '苏州市吴中太湖旅游区',
 '无锡市鼋头渚景区',
 '镇江市金山·焦山·北固山旅游景区',
 '镇江市金山·焦山·北固山旅游景区',
 '南通市濠河景区',
 '苏州市金鸡湖景区',
 '常州市环球恐龙城休闲旅游区',
 '扬州市瘦西湖风景区',
 '南京市夫子庙·秦淮风光带景区',
 '无锡市灵山景区',
 '无锡市灵山景区',
 '苏州市同里古镇景区',
 '苏州市同里古镇景区',
 '苏州市周庄古镇景区',
 '苏州市周庄古镇景区',
 '苏州园林',
 '中央电视台无锡影视基地三国水浒景区',
 '南京市钟山风景名胜区·中山陵园风景区',
 '南京市钟山风景名胜区·中山陵园风景区',
 '浙江省丽水市缙云仙都景区',
 '宁波市天一阁·月湖景区',
 '嘉兴市西塘古镇旅游景区',
 '衢州市江郎山·廿八都景区',
 '衢州市江郎山·廿八都景区',
 '台州市神仙居景区',
 '台州市天台山景区',
 '湖州市南浔古镇景区',
 '衢州市开化根宫佛国文化旅游景区',
 '绍兴市鲁迅故里沈园景区',
 '绍兴市鲁迅故里沈园景区',
 '杭州市西溪湿地旅游区',
 '嘉兴市南湖旅游区',
 '金华市东阳横店影视城景区',
 '嘉兴市桐乡乌镇古镇旅游区',
 '宁波市奉化溪口·滕头旅游景区',
 '杭州市千岛湖风景名胜区',
 '舟山市普陀山风景名胜区',
 '温州市雁荡山风景名胜区',
 '杭州市西湖风景名胜区',
 '六安市万佛湖景区',
 '芜湖市方特旅游区',
 '合肥市三河古镇景区',
 '黄山市古徽州文化旅游区',
 '阜阳市颍上八里河景区',
 '宣城市绩溪龙川景区',
 '六安市天堂寨旅游景区',
 '六安市天堂寨旅游景区',
 '六安市天堂寨旅游景区',
 '安庆市天柱山风景区',
 '黄山市皖南古村落·西递宏村',
 '池州市九华山风景区',
 '黄山市黄山风景区',
 '龙岩市古田旅游区',
 '福州市三坊七巷景区',
 '宁德市福鼎太姥山旅游区',
 '泉州市清源山景区',
 '泉州市清源山景区',
 '宁德市白水洋·鸳鸯溪旅游区',
 '宁德市白水洋·鸳鸯溪旅游区',
 '福建省土楼（永定·南靖）旅游景区',
 '三明市泰宁风景名胜区',
 '南平市武夷山风景名胜区',
 '厦门市鼓浪屿风景名胜区',
 '江西省萍乡市武功山景区',
 '南昌市滕王阁旅游区',
 '抚州市大觉山景区',
 '上饶市龟峰景区',
 '瑞金市共和国摇篮旅游区',
 '瑞金市共和国摇篮旅游区',
 '宜春市明月山旅游区',
 '景德镇市古窑民俗博览区',
 '景德镇市古窑民俗博览区',
 '景德镇市古窑民俗博览区',
 '上饶市婺源江湾景区',
 '鹰潭市龙虎山旅游景区',
 '上饶市三清山旅游景区',
 '上饶市三清山旅游景区',
 '上饶市三清山旅游景区',
 '上饶市三清山旅游景区',
 '上饶市三清山旅游景区',
 '吉安市井冈山风景旅游区',
 '九江市庐山风景名胜区',
 '九江市庐山风景名胜区',
 '九江市庐山风景名胜区',
 '九江市庐山风景名胜区',
 '山东省东营市黄河口生态旅游区',
 '青州市青州古城景区',
 '威海市华夏城景区',
 '山东省沂蒙山旅游区',
 '山东省沂蒙山旅游区',
 '山东省沂蒙山旅游区',
 '济南市天下第一泉景区',
 '枣庄市台儿庄古城景区',
 '威海市刘公岛景区',
 '烟台市龙口南山景区',
 '青岛市崂山景区',
 '泰安市泰山景区',
 '泰安市泰山景区',
 '泰安市泰山景区',
 '泰安市泰山景区',
 '济宁市曲阜明故城（三孔）旅游区',
 '烟台市蓬莱阁旅游区(三仙山·八仙过海)',
 '烟台市蓬莱阁旅游区(三仙山·八仙过海)',
 '烟台市蓬莱阁旅游区(三仙山·八仙过海)',
 '烟台市蓬莱阁旅游区(三仙山·八仙过海)',
 '河南省新乡市八里沟景区',
 '安阳市红旗渠·太行大峡谷旅游景区',
 '安阳市红旗渠·太行大峡谷旅游景区',
 '驻马店市嵖岈山旅游景区',
 '南阳市西峡伏牛山老界岭·恐龙遗址园旅游区',
 '南阳市西峡伏牛山老界岭·恐龙遗址园旅游区',
 '洛阳市龙潭大峡谷景区',
 '河南省洛阳栾川老君山·鸡冠洞旅游区',
 '河南省洛阳栾川老君山·鸡冠洞旅游区',
 '平顶山市尧山·中原大佛景区',
 '平顶山市尧山·中原大佛景区',
 '安阳市殷墟景区',
 '安阳市殷墟景区',
 '安阳市殷墟景区',
 '洛阳市白云山景区',
 '开封市清明上河园',
 '焦作市（云台山·神农山·青天河）风景名胜区',
 '焦作市（云台山·神农山·青天河）风景名胜区',
 '焦作市（云台山·神农山·青天河）风景名胜区',
 '洛阳市龙门石窟景区',
 '登封市嵩山少林景区',
 '湖北省襄阳市古隆中景区',
 '咸宁市赤壁市三国赤壁古战场景区',
 '恩施州恩施大峡谷景区',
 '武汉市黄陂木兰文化生态旅游区',
 '武汉市东湖景区',
 '武汉市东湖景区',
 '武汉市东湖景区',
 '宜昌市长阳清江画廊景区',
 '神农架风景区',
 '湖北省恩施州神龙溪纤夫文化旅游区',
 '湖北省恩施州神龙溪纤夫文化旅游区',
 '宜昌市三峡人家风景区',
 '十堰市武当山风景区',
 '宜昌市三峡大坝·屈原故里旅游区',
 '宜昌市三峡大坝·屈原故里旅游区',
 '宜昌市三峡大坝·屈原故里旅游区',
 '宜昌市三峡大坝·屈原故里旅游区',
 '宜昌市三峡大坝·屈原故里旅游区',
 '武汉市黄鹤楼公园',
 '湖南省株洲市炎帝陵景区',
 '湖南省株洲市炎帝陵景区',
 '邵阳市崀山景区',
 '郴州市东江湖旅游区',
 '长沙市花明楼景区',
 '长沙市花明楼景区',
 '长沙市岳麓山·橘子洲旅游区',
 '长沙市岳麓山·橘子洲旅游区',
 '长沙市岳麓山·橘子洲旅游区',
 '湘潭市韶山旅游区',
 '岳阳市岳阳楼·君山岛景区',
 '岳阳市岳阳楼·君山岛景区',
 '张家界市武陵源·天门山旅游区',
 '张家界市武陵源·天门山旅游区',
 '张家界市武陵源·天门山旅游区',
 '衡阳市南岳衡山旅游区',
 '广东省肇庆市星湖旅游景区',
 '惠州市惠州西湖旅游景区',
 '中山市孙中山故里旅游区',
 '阳江市海陵岛大角湾海上丝路旅游区',
 '惠州市罗浮山景区',
 '佛山市长鹿旅游休博园',
 '佛山市长鹿旅游休博园',
 '佛山市长鹿旅游休博园',
 '佛山市西樵山景区',
 '佛山市西樵山景区',
 '佛山市西樵山景区',
 '佛山市西樵山景区',
 '中国丹霞山世界地质公园',
 '清远市连州地下河旅游景区',
 '广州市白云山风景区',
 '梅州市雁南飞茶田景区',
 '梅州市雁南飞茶田景区',
 '梅州市雁南飞茶田景区',
 '深圳市观澜湖休闲旅游区',
 '深圳市华侨城旅游度假区',
 '广州市长隆旅游度假区',
 '广西壮族自治区百色市百色起义纪念园景区',
 '崇左市德天跨国瀑布景区',
 '崇左市德天跨国瀑布景区',
 '桂林市两江四湖·象山景区',
 '桂林市两江四湖·象山景区',
 '南宁市青秀山旅游区',
 '桂林市独秀峰·王城景区',
 '桂林市独秀峰·王城景区',
 '桂林市乐满地度假世界',
 '桂林市漓江景区',
 '三亚市蜈支洲岛旅游区',
 '海南槟榔谷黎苗文化旅游区',
 '分界洲岛旅游区',
 '海南呀诺达雨林文化旅游区',
 '海南呀诺达雨林文化旅游区',
 '三亚市南山大小洞天旅游区',
 '三亚市南山大小洞天旅游区',
 '三亚市南山大小洞天旅游区',
 '三亚市南山文化旅游区',
 '三亚市南山文化旅游区',
 '三亚市南山文化旅游区',
 '重庆市彭水县阿依河景区',
 '重庆市彭水县阿依河景区',
 '云阳龙缸风景区',
 '云阳龙缸风景区',
 '江津四面山景区',
 '江津四面山景区',
 '南川金佛山',
 '南川金佛山',
 '万盛经开区黑山谷景区',
 '酉阳桃花源旅游景区',
 '武隆喀斯特旅游区(天生三桥·仙女山·芙蓉洞)',
 '武隆喀斯特旅游区(天生三桥·仙女山·芙蓉洞)',
 '巫山小三峡·小小三峡',
 '巫山小三峡·小小三峡',
 '大足石刻景区',
 '大足石刻景区',
 '四川省雅安市碧峰峡旅游景区',
 '四川省甘孜州海螺沟景区',
 '南充市仪陇朱德故里景区',
 '南充市仪陇朱德故里景区',
 '广元市剑门蜀道剑门关旅游区',
 '阿坝州汶川特别旅游区',
 '绵阳市北川羌城旅游区',
 '南充市阆中古城旅游区',
 '广安市邓小平故里旅游区',
 '阿坝州黄龙景区',
 '乐山市乐山大佛景区',
 '阿坝藏族羌族自治州九寨沟旅游景区',
 '乐山市峨眉山景区',
 '乐山市峨眉山景区',
 '成都市青城山·都江堰旅游景区',
 '成都市青城山·都江堰旅游景区',
 '贵州省黔东南州镇远古城旅游景区',
 '贵州省黔东南州镇远古城旅游景区',
 '铜仁市梵净山（江口·印江）旅游区',
 '铜仁市梵净山（江口·印江）旅游区',
 '铜仁市梵净山（江口·印江）旅游区',
 '贵阳市花溪青岩古镇景区',
 '黔南州荔波樟江景区',
 '黔南州荔波樟江景区',
 '毕节市百里杜鹃景区',
 '安顺市龙宫景区',
 '安顺市黄果树大瀑布景区',
 '保山市腾冲火山热海旅游区',
 '昆明市昆明世博园景区',
 '迪庆州香格里拉普拉措景区',
 '大理市崇圣寺三塔文化旅游区',
 '丽江市丽江古城景区',
 '中国科学院西双版纳热带植物园',
 '丽江市玉龙雪山景区',
 '昆明市石林风景区',
 '林芝市巴松措景区',
 '林芝市巴松措景区',
 '日喀则市扎什伦布寺景区',
 '拉萨市大昭寺',
 '拉萨布达拉宫景区',
 '陕西省延安市延安革命纪念地景区',
 '西安市城墙·碑林历史文化景区',
 '宝鸡市太白山旅游景区',
 '商洛市金丝峡景区',
 '宝鸡市法门寺佛文化景区',
 '西安市大雁塔·大唐芙蓉园景区',
 '西安市大雁塔·大唐芙蓉园景区',
 '渭南市华山景区',
 '渭南市华山景区',
 '渭南市华山景区',
 '延安市黄帝陵景区',
 '西安市华清池景区',
 '西安市秦始皇兵马俑博物馆',
 '甘肃省张掖市七彩丹霞景区',
 '甘肃省张掖市七彩丹霞景区',
 '酒泉市敦煌鸣沙山月牙泉景区',
 '天水市麦积山景区',
 '平凉市崆峒山风景名胜区',
 '平凉市崆峒山风景名胜区',
 '嘉峪关市嘉峪关文物景区',
 '海东市互助土族故土园旅游区',
 '西宁市塔尔寺景区',
 '青海湖景区',
 '银川市灵武水洞沟旅游区',
 '银川市灵武水洞沟旅游区',
 '银川市镇北堡西部影视城',
 '中卫市沙坡头旅游景区',
 '石嘴山市沙湖旅游景区',
 '新疆维吾尔自治区喀什地区帕米尔旅游区',
 '新疆维吾尔自治区喀什地区帕米尔旅游区',
 '新疆生产建设兵团第十师白沙湖景区',
 '伊犁哈萨克自治州喀拉峻景区',
 '巴音郭楞蒙古自治州和静县巴音布鲁克景区',
 '喀什地区喀什噶尔老城景区',
 '乌鲁木齐市天山大峡谷景区',
 '乌鲁木齐市天山大峡谷景区',
 '巴音郭楞蒙古自治州博斯腾湖景区',
 '巴音郭楞蒙古自治州博斯腾湖景区',
 '喀什地区泽普金湖杨景区',
 '伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区',
 '伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区',
 '伊犁哈萨克自治州那拉提旅游风景区',
 '伊犁哈萨克自治州阿勒泰地区喀纳斯景区',
 '吐鲁番市葡萄沟风景区',
 '昌吉回族自治州阜康市天山天池风景名胜区']

In [23]:
dict_scence = {}
data_scence = pd.DataFrame(dict_scence)

# sceneID | scenename    | scenecity | sceneurl



data_scence['scence_id'] = list_scence_id
data_scence['scenename'] = list_scenename
data_scence['scenecity'] = list_scenecity 
data_scence['sceneurl'] = list_sceneurl

data_scence

,scence_id,scenename,scenecity,sceneurl
0,1001,圆明园,北京,https://weibo.com/p/100101B2094654D66EA3FE439C
1,1002,奥林匹克公园,北京,http://weibo.com/p/100101B2094251D064A6F9439D
2,1003,恭王府景区,北京,https://weibo.com/p/100101B2094757D06EAAFD489E
3,1004,北京市明十三陵景区,北京,https://weibo.com/p/100101B2094654D365A4FC4392
4,1004,北京市明十三陵景区,北京,https://weibo.com/p/100101B2094450DA68A4F54199
...,...,...,...,...
371,1368,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,伊犁哈萨克自治州,https://weibo.com/p/100101B2094757D16FA7FF449F
372,1369,伊犁哈萨克自治州那拉提旅游风景区,伊犁哈萨克自治州,http://weibo.com/p/100101B2094252D064A2F8429E
373,1370,伊犁哈萨克自治州阿勒泰地区喀纳斯景区,伊犁哈萨克自治州,https://weibo.com/p/100101B2094757D065A2FA439D
374,1371,吐鲁番市葡萄沟风景区,吐鲁番市,http://weibo.com/p/100101B209465CDA6FA4FF4598
375,1372,昌吉回族自治州阜康市天山天池风景名胜区,昌吉回族自治州,https://weibo.com/p/100101B2094757D06FABFD499E

In [24]:
# 将cityname的数据进行清洗
# ID | origin | new  | url
import pymysql
import pandas as pd
#连接数据库
conn=pymysql.connect(host = '127.0.0.1' # 连接名称，默认127.0.0.1
,user = 'root' # 用户名
,passwd='123456' # 密码
,port= 3306 # 端口，默认为3306
,db='weibo0223' # 数据库的名字
,charset='utf8' # 字符编码
)
cur = conn.cursor() # 生成游标对象
sql="select * from `cityname`  " # SQL语句
cur.execute(sql) # 执行SQL语句
data_cityname = cur.fetchall() # 通过fetchall方法获得数据
for i in data_cityname[:20]: # 打印输出前3条数据
    print(i)
# cur.close() # 关闭游标
# conn.close() # 关闭连接

(1, '北京', '北京', 'http://www.tianqihoubao.com/lishi/beijing.html')
(2, '天津', '天津', 'http://www.tianqihoubao.com/lishi/tianjin.html')
(3, '保定市', '保定', 'http://www.tianqihoubao.com/lishi/baoding.html')
(4, '秦皇岛市', '秦皇岛', 'http://www.tianqihoubao.com/lishi/qinhuangdao.html')
(5, '邯郸市', '邯郸', 'http://www.tianqihoubao.com/lishi/handan.html')
(6, '唐山市', '唐山', 'http://www.tianqihoubao.com/lishi/tangshan.html')
(7, '石家庄市', '石家庄', 'http://www.tianqihoubao.com/lishi/shijiazhuang.html')
(8, '承德市', '承德', 'http://www.tianqihoubao.com/lishi/chengde.html')
(9, '长治市', '长治', 'http://www.tianqihoubao.com/lishi/changzhi.html')
(10, '临汾市', '临汾', 'http://www.tianqihoubao.com/lishi/linfen.html')
(11, '忻州市', '忻州', 'http://www.tianqihoubao.com/lishi/xinzhou.html')
(12, '晋中市', '晋中', 'http://www.tianqihoubao.com/lishi/jinzhong.html')
(13, '晋城市', '晋城', 'http://www.tianqihoubao.com/lishi/jincheng.html')
(14, '大同市', '大同', 'http://www.tianqihoubao.com/lishi/datong.html')
(15, '额济纳旗额济纳', '阿拉善盟', 'http://www.tianqihoubao.com/lishi/alashanmeng.html')
(16, '赤峰市', '赤峰', 'http://www.tianqihoubao.com/lishi/chifeng.html')
(17, '兴安盟阿尔山市', '兴安盟', 'http://www.tianqihoubao.com/lishi/xinganmeng.html')
(18, '满洲里市', '呼伦贝尔', 'http://www.tianqihoubao.com/lishi/hulunbeier.html')
(19, '鄂尔多斯市', '鄂尔多斯', 'http://www.tianqihoubao.com/lishi/eerduosi.html')
(20, '盘锦市', '盘锦', 'http://www.tianqihoubao.com/lishi/panjin.html')

In [25]:
# ID | origin | new  | url


list_origin_cityname = []
list_new_cityname = []

for items in data_cityname:
    origin_cityname = items[1]
    new_cityname = items[2]

#     scence_id = scence_id.strip()
    origin_cityname = origin_cityname.strip()
    new_cityname = new_cityname.strip()
    
    list_origin_cityname.append(origin_cityname)
    list_new_cityname.append(new_cityname)

    
print(len(list_origin_cityname))
print(len(list_new_cityname))

182
182

In [26]:
dict_cityname = {}
data_cityname = pd.DataFrame(dict_cityname)

# ID | origin | new  | url


data_cityname['origin_cityname'] = list_origin_cityname
data_cityname['new_cityname'] = list_new_cityname

data_cityname

    origin_cityname new_cityname
0                北京           北京
1                天津           天津
2               保定市           保定
3              秦皇岛市          秦皇岛
4               邯郸市           邯郸
..              ...          ...
177       巴音郭楞蒙古自治州          吐鲁番
178            喀什地区           喀什
179           乌鲁木齐市         乌鲁木齐
180            吐鲁番市          吐鲁番
181         昌吉回族自治州           昌吉

[182 rows x 2 columns]

In [27]:
# 将data_cityname和data_scence聚合
data_cityname_scence = pd.merge(data_cityname, data_scence,left_on = 'origin_cityname',right_on = 'scenecity',how = 'right')

In [36]:
data_cityname_scence['scenename'] = [x.strip() for x in data_cityname_scence['scenename']]

In [37]:
df4['scence_name1'] = [x.strip() for x in df4['scence_name']]
df4['scence_name1']

0                           圆明园
1                           圆明园
2                           圆明园
3                           圆明园
4                           圆明园
                  ...
335760    伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区
335761    伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区
335762    伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区
335763    伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区
335764    伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区
Name: scence_name1, Length: 335765, dtype: object

In [47]:
# origin_cityname	new_cityname	scence_id	scenename
data_cityname_scence1 = data_cityname_scence[['origin_cityname','new_cityname','scence_id','scenename']]
data_cityname_scence2 = data_cityname_scence1.drop_duplicates()

In [48]:
data_cityname_scence2

    origin_cityname new_cityname scence_id              scenename
0                北京           北京      1001                    圆明园
1                北京           北京      1002                 奥林匹克公园
2                北京           北京      1003                  恭王府景区
3                北京           北京      1004              北京市明十三陵景区
6                北京           北京      1005         北京八达岭－慕田峪长城旅游区
..              ...          ...       ...                    ...
370        伊犁哈萨克自治州           伊犁      1368  伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区
372        伊犁哈萨克自治州           伊犁      1369       伊犁哈萨克自治州那拉提旅游风景区
373        伊犁哈萨克自治州           伊犁      1370     伊犁哈萨克自治州阿勒泰地区喀纳斯景区
374            吐鲁番市          吐鲁番      1371             吐鲁番市葡萄沟风景区
375         昌吉回族自治州           昌吉      1372    昌吉回族自治州阜康市天山天池风景名胜区

[274 rows x 4 columns]

In [63]:
# 将评论的全部数据df4的scence_name 与data_cityname_scence的scenename聚合
df5 = pd.merge(df4,data_cityname_scence2,left_on = 'scence_name1',right_on = 'scenename',how = 'left')

In [64]:
df5

,comment_id,comment_time,scence_name,comment_detail,Positive,Neutral,Negative,Sentiment,RequestId,sentiment_score,scence_name1,origin_cityname,new_cityname,scence_id,scenename
0,1451,2022-11-25,圆明园,明天就要降温了今天风好大,27.513403,51.240921,21.248679,neutral,c4e80585-89fa-4c15-bada-f23957e8ec65,51.240921,圆明园,北京,北京,1001,圆明园
1,1452,2022-11-25,圆明园,这样能封一辈子吗病毒没死几个人防疫倒是快把人折磨死了,2.416031,8.446255,89.140707,negative,30495bee-4108-4461-b40f-b42f98ff7dc8,89.140707,圆明园,北京,北京,1001,圆明园
2,1453,2022-11-25,圆明园,圆明园被烧十二年后长春园西洋楼花园门残影摄于公元1873同治十二年,43.924150,54.498631,1.580220,neutral,b0798e05-fea4-4dfa-94cf-49f3cc3657e8,54.498631,圆明园,北京,北京,1001,圆明园
3,1454,2022-11-25,圆明园,分享图片,0.056465,99.927229,0.019305,neutral,ae886551-4939-4b56-8ec6-3d40e4d119e1,99.927229,圆明园,北京,北京,1001,圆明园
4,1455,2022-11-25,圆明园,吃完饭坐上坐骑真舒服呀,99.985266,0.016083,0.001650,positive,75417462-afad-444c-8983-f21f633fe577,99.985266,圆明园,北京,北京,1001,圆明园
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335760,256224,2021-09-21,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,DAY3 可可托海镇-可可托海风景区（额尔齐斯大峡谷），徒步10公里，聆听额尔齐斯河的欢歌，...,71.821064,20.475243,7.706693,positive,43d591a4-b520-4113-b870-eeb2e9c1d9df,71.821064,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,伊犁哈萨克自治州,伊犁,1368,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区
335761,256224,2021-09-21,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,的树林，额尔齐斯河时而咆哮时而蜿蜒，一路向北，奔向北冰洋。透明的黄，深沉的黄在河边和峡谷弥漫...,63.880837,22.737600,13.384573,positive,ee7e3435-1218-484c-842a-ad59e6330be9,63.880837,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,伊犁哈萨克自治州,伊犁,1368,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区
335762,256224,2021-09-21,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,票价10元，整个景区用时约7小时左右。最佳观赏期每年9.20-10.7之间。,80.376095,14.673571,4.953333,positive,e59dcfd6-414d-4395-8900-2315af404811,80.376095,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,伊犁哈萨克自治州,伊犁,1368,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区
335763,256317,2019-07-19,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,当第一缕阳光崩出天际，可可托海的生物们又迎来了崭新的一天。谁是早起冠军呢？是漫步山野之间的牛...,29.673469,61.576158,8.753374,neutral,48b14b35-91b1-40f0-9ef1-23768bc447ab,61.576158,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,伊犁哈萨克自治州,伊犁,1368,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区
335764,256317,2019-07-19,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,见他一眼就会迷恋上那双透彻的眼睛，直射人心，重击灵魂。,21.208419,74.240619,4.553967,neutral,8c62b25b-ea62-4ddc-9047-f3cbf478fd63,74.240619,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,伊犁哈萨克自治州,伊犁,1368,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区

In [65]:
from datetime import datetime
def string_to_date(string1):
    string1 = string1.strip()
    date_object1 = datetime.strptime(string1, '%Y-%m-%d')
    return date_object1
df5['comment_day'] =  df5['comment_time'].apply(string_to_date)
df5['comment_day']

0        2022-11-25
1        2022-11-25
2        2022-11-25
3        2022-11-25
4        2022-11-25
            ...
335760   2021-09-21
335761   2021-09-21
335762   2021-09-21
335763   2019-07-19
335764   2019-07-19
Name: comment_day, Length: 335765, dtype: datetime64[ns]

In [66]:
data_weather = pd.read_csv('E:\\论文\\第二篇论文\\截止到2023年2月数据汇总\\天气的总数据.csv',encoding = 'utf-8-sig')
data_weather

,Unnamed: 0,scence_id,scence_city,scence_date,low_temperature,high_temperature,weather_type,wind,weather1,weather2
0,0,1352,天津,20190601,21,31,阵雨/阴,东南风1-2级/东南风1-2级,阵雨,阴
1,1,1353,天津,20190602,22,34,阴/雷阵雨,西南风3-4级/西南风3-4级,阴,雷阵雨
2,2,1354,天津,20190603,21,32,多云/阴,东南风3-4级/东南风3-4级,多云,阴
3,3,1355,天津,20190604,21,27,雷阵雨/雷阵雨,东风4-5级/东风4-5级,雷阵雨,雷阵雨
4,4,1356,天津,20190605,19,27,阴/中雨,东北风3-4级/东北风3-4级,阴,中雨
...,...,...,...,...,...,...,...,...,...,...
231435,231435,251002,呼伦贝尔,20221227,-27,-21,多云/小雪,西北风1-2级/西北风1-2级,多云,小雪
231436,231436,251003,呼伦贝尔,20221228,-32,-22,小雪/晴,西风3-4级/西风3-4级,小雪,晴
231437,231437,251004,呼伦贝尔,20221229,-30,-21,晴/晴,西风3-4级/西风1-2级,晴,晴
231438,231438,251005,呼伦贝尔,20221230,-26,-16,晴/晴,西南风3-4级/西风3-4级,晴,晴
231439,231439,251006,呼伦贝尔,20221231,-30,-19,晴/晴,西风3-4级/西风3-4级,晴,晴

In [67]:
from datetime import datetime
def commentday_to_date(string1):
    string1 = str(string1)
    string2 = string1[:4]+'-'+string1[4:6]+'-'+string1[6:8]
    date_object1 = datetime.strptime(string2, '%Y-%m-%d')
    return date_object1
data_weather['comment_day'] = data_weather['scence_date'].apply(commentday_to_date)
data_weather['comment_day']

0        2019-06-01
1        2019-06-02
2        2019-06-03
3        2019-06-04
4        2019-06-05
            ...
231435   2022-12-27
231436   2022-12-28
231437   2022-12-29
231438   2022-12-30
231439   2022-12-31
Name: comment_day, Length: 231440, dtype: datetime64[ns]

In [68]:
# # scence_id	scence_city	scence_date	low_temperature	high_temperature	weather_type	wind	weather1	weather2	comment_day
# data_weather1 = data_weather[['scence_id','scence_city','low_temperature','high_temperature','wind','weather1','weather2','comment_day']]
print(type(data_weather['comment_day'].iloc[2]))
print(type(df5['comment_day'].iloc[2]))

<class 'pandas._libs.tslibs.timestamps.Timestamp'>
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [69]:
# 将df5数据与天气数据相聚合
df6 = pd.merge(df5,data_weather,left_on =('new_cityname','comment_day'),right_on =('scence_city','comment_day'),how = 'inner')

In [70]:
df6.to_csv('E:\\论文\\第二篇论文\\截止到2023年2月数据汇总\\评论天气城市数据的总和.csv',encoding = 'utf-8')

In [83]:
df6.columns

Index(['comment_id', 'comment_time', 'scence_name', 'comment_detail',
       'Positive', 'Neutral', 'Negative', 'Sentiment', 'RequestId',
       'sentiment_score', 'scence_name1', 'origin_cityname', 'new_cityname',
       'scence_id_x', 'scenename', 'comment_day', 'Unnamed: 0', 'scence_id_y',
       'scence_city', 'scence_date', 'low_temperature', 'high_temperature',
       'weather_type', 'wind', 'weather1', 'weather2'],
      dtype='object')

## 打开之前的全部数据

## 设置holiday指标
## 设置month指标
## 设置period指标

In [73]:
# 'comment_time'
# 'scence_name'
# 'comment_detail'
# 'Positive'
# 'Neutral'
# 'Negative'
# 'Sentiment'
# 'scence_name1'
# 'origin_cityname'
# 'new_cityname'
# 'comment_day'
# 'low_temperature'
# 'high_temperature'
# 'weather_type'
# 'wind'
# 'weather1'
# 'weather2'

2586

In [87]:
df7 = df6[['comment_time','scence_name','comment_detail','Positive','Neutral','Negative','Sentiment','scence_name1','origin_cityname','new_cityname','comment_day','low_temperature','high_temperature', 'weather_type', 'wind', 'weather1','weather2',]]
df7['comment_time'] = [x.strip() for x in df7['comment_time']]
df7[ 'scence_name'] = [x.strip() for x in df7[ 'scence_name']]
df7[ 'comment_detail'] = [x.strip() for x in df7[ 'comment_detail']]
# df7[ 'Positive'] = [x.strip() for x in df7[ 'Positive']]
# df7[ 'Neutral'] = [x.strip() for x in df7[ 'Neutral']]
# df7['Negative'] = [x.strip() for x in df7['Negative']]
df7[ 'Sentiment'] = [x.strip() for x in df7[ 'Sentiment']]
df7[  'origin_cityname'] = [x.strip() for x in df7[  'origin_cityname']]
df7[' new_cityname'] = [x.strip() for x in df7[ 'new_cityname']]
# df7[  'low_temperature'] = [x.strip() for x in df7[  'low_temperature']]
# df7[ 'high_temperature'] = [x.strip() for x in df7[ 'high_temperature']]
df7[ 'weather_type'] = [x.strip() for x in df7[ 'weather_type']]
df7[ 'wind'] = [x.strip() for x in df7[ 'wind']]
df7[ 'weather1'] = [x.strip() for x in df7[ 'weather1']]
df7['weather2'] = [x.strip() for x in df7['weather2']]
df7

,comment_time,scence_name,comment_detail,Positive,Neutral,Negative,Sentiment,scence_name1,origin_cityname,new_cityname,comment_day,low_temperature,high_temperature,weather_type,wind,weather1,weather2,new_cityname
0,2022-11-25,圆明园,明天就要降温了今天风好大,27.513403,51.240921,21.248679,neutral,圆明园,北京,北京,2022-11-25,-2,14,晴/多云,西北风3-4级/西北风3-4级,晴,多云,北京
1,2022-11-25,圆明园,这样能封一辈子吗病毒没死几个人防疫倒是快把人折磨死了,2.416031,8.446255,89.140707,negative,圆明园,北京,北京,2022-11-25,-2,14,晴/多云,西北风3-4级/西北风3-4级,晴,多云,北京
2,2022-11-25,圆明园,圆明园被烧十二年后长春园西洋楼花园门残影摄于公元1873同治十二年,43.924150,54.498631,1.580220,neutral,圆明园,北京,北京,2022-11-25,-2,14,晴/多云,西北风3-4级/西北风3-4级,晴,多云,北京
3,2022-11-25,圆明园,分享图片,0.056465,99.927229,0.019305,neutral,圆明园,北京,北京,2022-11-25,-2,14,晴/多云,西北风3-4级/西北风3-4级,晴,多云,北京
4,2022-11-25,圆明园,吃完饭坐上坐骑真舒服呀,99.985266,0.016083,0.001650,positive,圆明园,北京,北京,2022-11-25,-2,14,晴/多云,西北风3-4级/西北风3-4级,晴,多云,北京
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314930,2022-12-06,巴音郭楞蒙古自治州博斯腾湖景区,【湖面长满片片“鱼鳞” 博斯腾湖出现冰冻奇观】12月5日，受近期寒潮低温天气影响，博斯腾湖湖...,58.925056,32.101324,8.976624,positive,巴音郭楞蒙古自治州博斯腾湖景区,巴音郭楞蒙古自治州,吐鲁番,2022-12-06,-8,0,晴/多云,北风1-2级/北风1-2级,晴,多云,吐鲁番
314931,2022-12-06,巴音郭楞蒙古自治州博斯腾湖景区,候只看到岸边的一点点冰块，今年这么多的冰层我还是第一次见到，风一吹像鱼儿一样在游动，这样奇特...,42.487818,33.195922,24.319269,positive,巴音郭楞蒙古自治州博斯腾湖景区,巴音郭楞蒙古自治州,吐鲁番,2022-12-06,-8,0,晴/多云,北风1-2级/北风1-2级,晴,多云,吐鲁番
314932,2022-12-06,巴音郭楞蒙古自治州博斯腾湖景区,的冰随着流动的水面堆积，形成了这一壮观的景象，另外此次寒潮天气使开都河提早出现了冰凌现象。”...,51.249945,23.455395,25.297660,positive,巴音郭楞蒙古自治州博斯腾湖景区,巴音郭楞蒙古自治州,吐鲁番,2022-12-06,-8,0,晴/多云,北风1-2级/北风1-2级,晴,多云,吐鲁番
314933,2021-10-26,巴音郭楞蒙古自治州博斯腾湖景区,"""【新疆秋之韵：博斯腾湖芦苇摇曳，水鸟成群】博斯腾湖是中国最大的内陆淡水湖。环湖孕育着60万...",43.162942,43.066442,13.773608,positive,巴音郭楞蒙古自治州博斯腾湖景区,巴音郭楞蒙古自治州,吐鲁番,2021-10-26,7,17,晴/晴,北风1-2级/北风1-2级,晴,晴,吐鲁番
314934,2021-10-26,巴音郭楞蒙古自治州博斯腾湖景区,ygur Autonomous Region,55.979103,32.504731,11.519170,positive,巴音郭楞蒙古自治州博斯腾湖景区,巴音郭楞蒙古自治州,吐鲁番,2021-10-26,7,17,晴/晴,北风1-2级/北风1-2级,晴,晴,吐鲁番

In [96]:
date_holiday = pd.read_csv('E:\\论文\\第二篇论文\\截止到2023年2月数据汇总\\date_holiday.csv',encoding = 'utf-8-sig') #1341

In [101]:
from datetime import datetime
def string_to_date(string1):
    string1 = string1.strip()
    date_object1 = datetime.strptime(string1, '%Y-%m-%d')
    return date_object1

date_holiday['date'] = date_holiday['date'].apply(string_to_date)

In [103]:
df8 = pd.merge(df7,date_holiday,left_on = 'comment_day',right_on = 'date',how = 'left')

In [107]:
# 对时间段进行划分
def period_segment(string1):
    string1 = str(string1)
    if string1<'2020-01-23':
        period = 0
    elif string1<'2020-04-22':
        period = 1
    elif string1<'2020-11-09':
        period = 2
    elif string1<'2021-05-17':
        period = 3
    elif string1<'2022-08-04':
        period = 4
    elif string1<'2022-12-06':
        period = 5  
    else:
        period = 6      
    return period
df8['period'] =  df8['comment_day'].apply(period_segment)
df8

,comment_time,scence_name,comment_detail,Positive,Neutral,Negative,Sentiment,scence_name1,origin_cityname,new_cityname,...,low_temperature,high_temperature,weather_type,wind,weather1,weather2,new_cityname,date,holiday,period
0,2022-11-25,圆明园,明天就要降温了今天风好大,27.513403,51.240921,21.248679,neutral,圆明园,北京,北京,...,-2,14,晴/多云,西北风3-4级/西北风3-4级,晴,多云,北京,2022-11-25,0,5
1,2022-11-25,圆明园,这样能封一辈子吗病毒没死几个人防疫倒是快把人折磨死了,2.416031,8.446255,89.140707,negative,圆明园,北京,北京,...,-2,14,晴/多云,西北风3-4级/西北风3-4级,晴,多云,北京,2022-11-25,0,5
2,2022-11-25,圆明园,圆明园被烧十二年后长春园西洋楼花园门残影摄于公元1873同治十二年,43.924150,54.498631,1.580220,neutral,圆明园,北京,北京,...,-2,14,晴/多云,西北风3-4级/西北风3-4级,晴,多云,北京,2022-11-25,0,5
3,2022-11-25,圆明园,分享图片,0.056465,99.927229,0.019305,neutral,圆明园,北京,北京,...,-2,14,晴/多云,西北风3-4级/西北风3-4级,晴,多云,北京,2022-11-25,0,5
4,2022-11-25,圆明园,吃完饭坐上坐骑真舒服呀,99.985266,0.016083,0.001650,positive,圆明园,北京,北京,...,-2,14,晴/多云,西北风3-4级/西北风3-4级,晴,多云,北京,2022-11-25,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314930,2022-12-06,巴音郭楞蒙古自治州博斯腾湖景区,【湖面长满片片“鱼鳞” 博斯腾湖出现冰冻奇观】12月5日，受近期寒潮低温天气影响，博斯腾湖湖...,58.925056,32.101324,8.976624,positive,巴音郭楞蒙古自治州博斯腾湖景区,巴音郭楞蒙古自治州,吐鲁番,...,-8,0,晴/多云,北风1-2级/北风1-2级,晴,多云,吐鲁番,2022-12-06,0,6
314931,2022-12-06,巴音郭楞蒙古自治州博斯腾湖景区,候只看到岸边的一点点冰块，今年这么多的冰层我还是第一次见到，风一吹像鱼儿一样在游动，这样奇特...,42.487818,33.195922,24.319269,positive,巴音郭楞蒙古自治州博斯腾湖景区,巴音郭楞蒙古自治州,吐鲁番,...,-8,0,晴/多云,北风1-2级/北风1-2级,晴,多云,吐鲁番,2022-12-06,0,6
314932,2022-12-06,巴音郭楞蒙古自治州博斯腾湖景区,的冰随着流动的水面堆积，形成了这一壮观的景象，另外此次寒潮天气使开都河提早出现了冰凌现象。”...,51.249945,23.455395,25.297660,positive,巴音郭楞蒙古自治州博斯腾湖景区,巴音郭楞蒙古自治州,吐鲁番,...,-8,0,晴/多云,北风1-2级/北风1-2级,晴,多云,吐鲁番,2022-12-06,0,6
314933,2021-10-26,巴音郭楞蒙古自治州博斯腾湖景区,"""【新疆秋之韵：博斯腾湖芦苇摇曳，水鸟成群】博斯腾湖是中国最大的内陆淡水湖。环湖孕育着60万...",43.162942,43.066442,13.773608,positive,巴音郭楞蒙古自治州博斯腾湖景区,巴音郭楞蒙古自治州,吐鲁番,...,7,17,晴/晴,北风1-2级/北风1-2级,晴,晴,吐鲁番,2021-10-26,0,4
314934,2021-10-26,巴音郭楞蒙古自治州博斯腾湖景区,ygur Autonomous Region,55.979103,32.504731,11.519170,positive,巴音郭楞蒙古自治州博斯腾湖景区,巴音郭楞蒙古自治州,吐鲁番,...,7,17,晴/晴,北风1-2级/北风1-2级,晴,晴,吐鲁番,2021-10-26,0,4

In [109]:
df8['comment_day'].iloc[2].date().month

11

In [110]:
df8['month'] = [x.date().month for x in df8['comment_day']]
df8

,comment_time,scence_name,comment_detail,Positive,Neutral,Negative,Sentiment,scence_name1,origin_cityname,new_cityname,...,high_temperature,weather_type,wind,weather1,weather2,new_cityname,date,holiday,period,month
0,2022-11-25,圆明园,明天就要降温了今天风好大,27.513403,51.240921,21.248679,neutral,圆明园,北京,北京,...,14,晴/多云,西北风3-4级/西北风3-4级,晴,多云,北京,2022-11-25,0,5,11
1,2022-11-25,圆明园,这样能封一辈子吗病毒没死几个人防疫倒是快把人折磨死了,2.416031,8.446255,89.140707,negative,圆明园,北京,北京,...,14,晴/多云,西北风3-4级/西北风3-4级,晴,多云,北京,2022-11-25,0,5,11
2,2022-11-25,圆明园,圆明园被烧十二年后长春园西洋楼花园门残影摄于公元1873同治十二年,43.924150,54.498631,1.580220,neutral,圆明园,北京,北京,...,14,晴/多云,西北风3-4级/西北风3-4级,晴,多云,北京,2022-11-25,0,5,11
3,2022-11-25,圆明园,分享图片,0.056465,99.927229,0.019305,neutral,圆明园,北京,北京,...,14,晴/多云,西北风3-4级/西北风3-4级,晴,多云,北京,2022-11-25,0,5,11
4,2022-11-25,圆明园,吃完饭坐上坐骑真舒服呀,99.985266,0.016083,0.001650,positive,圆明园,北京,北京,...,14,晴/多云,西北风3-4级/西北风3-4级,晴,多云,北京,2022-11-25,0,5,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314930,2022-12-06,巴音郭楞蒙古自治州博斯腾湖景区,【湖面长满片片“鱼鳞” 博斯腾湖出现冰冻奇观】12月5日，受近期寒潮低温天气影响，博斯腾湖湖...,58.925056,32.101324,8.976624,positive,巴音郭楞蒙古自治州博斯腾湖景区,巴音郭楞蒙古自治州,吐鲁番,...,0,晴/多云,北风1-2级/北风1-2级,晴,多云,吐鲁番,2022-12-06,0,6,12
314931,2022-12-06,巴音郭楞蒙古自治州博斯腾湖景区,候只看到岸边的一点点冰块，今年这么多的冰层我还是第一次见到，风一吹像鱼儿一样在游动，这样奇特...,42.487818,33.195922,24.319269,positive,巴音郭楞蒙古自治州博斯腾湖景区,巴音郭楞蒙古自治州,吐鲁番,...,0,晴/多云,北风1-2级/北风1-2级,晴,多云,吐鲁番,2022-12-06,0,6,12
314932,2022-12-06,巴音郭楞蒙古自治州博斯腾湖景区,的冰随着流动的水面堆积，形成了这一壮观的景象，另外此次寒潮天气使开都河提早出现了冰凌现象。”...,51.249945,23.455395,25.297660,positive,巴音郭楞蒙古自治州博斯腾湖景区,巴音郭楞蒙古自治州,吐鲁番,...,0,晴/多云,北风1-2级/北风1-2级,晴,多云,吐鲁番,2022-12-06,0,6,12
314933,2021-10-26,巴音郭楞蒙古自治州博斯腾湖景区,"""【新疆秋之韵：博斯腾湖芦苇摇曳，水鸟成群】博斯腾湖是中国最大的内陆淡水湖。环湖孕育着60万...",43.162942,43.066442,13.773608,positive,巴音郭楞蒙古自治州博斯腾湖景区,巴音郭楞蒙古自治州,吐鲁番,...,17,晴/晴,北风1-2级/北风1-2级,晴,晴,吐鲁番,2021-10-26,0,4,10
314934,2021-10-26,巴音郭楞蒙古自治州博斯腾湖景区,ygur Autonomous Region,55.979103,32.504731,11.519170,positive,巴音郭楞蒙古自治州博斯腾湖景区,巴音郭楞蒙古自治州,吐鲁番,...,17,晴/晴,北风1-2级/北风1-2级,晴,晴,吐鲁番,2021-10-26,0,4,10

In [111]:
df8['outbreak'] = [0 for x in df8['comment_day'] if str(x) <'2020-01-23' else 1]

SyntaxError: invalid syntax (3321215750.py, line 1)

In [112]:
def outbreak_Date(datetime1):
    string1 = str(datetime1)
    if string1<'2020-01-23':
        int1 = 0
    else:
        int1 = 1
    return int1
df8['outbreak'] = df8['comment_day'].apply(outbreak_Date)
df8

,comment_time,scence_name,comment_detail,Positive,Neutral,Negative,Sentiment,scence_name1,origin_cityname,new_cityname,...,weather_type,wind,weather1,weather2,new_cityname,date,holiday,period,month,outbreak
0,2022-11-25,圆明园,明天就要降温了今天风好大,27.513403,51.240921,21.248679,neutral,圆明园,北京,北京,...,晴/多云,西北风3-4级/西北风3-4级,晴,多云,北京,2022-11-25,0,5,11,1
1,2022-11-25,圆明园,这样能封一辈子吗病毒没死几个人防疫倒是快把人折磨死了,2.416031,8.446255,89.140707,negative,圆明园,北京,北京,...,晴/多云,西北风3-4级/西北风3-4级,晴,多云,北京,2022-11-25,0,5,11,1
2,2022-11-25,圆明园,圆明园被烧十二年后长春园西洋楼花园门残影摄于公元1873同治十二年,43.924150,54.498631,1.580220,neutral,圆明园,北京,北京,...,晴/多云,西北风3-4级/西北风3-4级,晴,多云,北京,2022-11-25,0,5,11,1
3,2022-11-25,圆明园,分享图片,0.056465,99.927229,0.019305,neutral,圆明园,北京,北京,...,晴/多云,西北风3-4级/西北风3-4级,晴,多云,北京,2022-11-25,0,5,11,1
4,2022-11-25,圆明园,吃完饭坐上坐骑真舒服呀,99.985266,0.016083,0.001650,positive,圆明园,北京,北京,...,晴/多云,西北风3-4级/西北风3-4级,晴,多云,北京,2022-11-25,0,5,11,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314930,2022-12-06,巴音郭楞蒙古自治州博斯腾湖景区,【湖面长满片片“鱼鳞” 博斯腾湖出现冰冻奇观】12月5日，受近期寒潮低温天气影响，博斯腾湖湖...,58.925056,32.101324,8.976624,positive,巴音郭楞蒙古自治州博斯腾湖景区,巴音郭楞蒙古自治州,吐鲁番,...,晴/多云,北风1-2级/北风1-2级,晴,多云,吐鲁番,2022-12-06,0,6,12,1
314931,2022-12-06,巴音郭楞蒙古自治州博斯腾湖景区,候只看到岸边的一点点冰块，今年这么多的冰层我还是第一次见到，风一吹像鱼儿一样在游动，这样奇特...,42.487818,33.195922,24.319269,positive,巴音郭楞蒙古自治州博斯腾湖景区,巴音郭楞蒙古自治州,吐鲁番,...,晴/多云,北风1-2级/北风1-2级,晴,多云,吐鲁番,2022-12-06,0,6,12,1
314932,2022-12-06,巴音郭楞蒙古自治州博斯腾湖景区,的冰随着流动的水面堆积，形成了这一壮观的景象，另外此次寒潮天气使开都河提早出现了冰凌现象。”...,51.249945,23.455395,25.297660,positive,巴音郭楞蒙古自治州博斯腾湖景区,巴音郭楞蒙古自治州,吐鲁番,...,晴/多云,北风1-2级/北风1-2级,晴,多云,吐鲁番,2022-12-06,0,6,12,1
314933,2021-10-26,巴音郭楞蒙古自治州博斯腾湖景区,"""【新疆秋之韵：博斯腾湖芦苇摇曳，水鸟成群】博斯腾湖是中国最大的内陆淡水湖。环湖孕育着60万...",43.162942,43.066442,13.773608,positive,巴音郭楞蒙古自治州博斯腾湖景区,巴音郭楞蒙古自治州,吐鲁番,...,晴/晴,北风1-2级/北风1-2级,晴,晴,吐鲁番,2021-10-26,0,4,10,1
314934,2021-10-26,巴音郭楞蒙古自治州博斯腾湖景区,ygur Autonomous Region,55.979103,32.504731,11.519170,positive,巴音郭楞蒙古自治州博斯腾湖景区,巴音郭楞蒙古自治州,吐鲁番,...,晴/晴,北风1-2级/北风1-2级,晴,晴,吐鲁番,2021-10-26,0,4,10,1

In [113]:
set1 = set(df8['scence_name'])

In [114]:
len(set1)

273

In [116]:
dict1 = dict(zip(list(range(len(set1))), set1))
dict1

{0: '福州市三坊七巷景区',
 1: '桂林市漓江景区',
 2: '铜仁市梵净山（江口·印江）旅游区',
 3: '北京市明十三陵景区',
 4: '内蒙古自治区阿拉善盟胡杨林旅游区',
 5: '宁波市天一阁·月湖景区',
 6: '青州市青州古城景区',
 7: '三明市泰宁风景名胜区',
 8: '南充市仪陇朱德故里景区',
 9: '宁德市福鼎太姥山旅游区',
 10: '湖北省襄阳市古隆中景区',
 11: '昆明市昆明世博园景区',
 12: '杭州市西溪湿地旅游区',
 13: '阜阳市颍上八里河景区',
 14: '郴州市东江湖旅游区',
 15: '宁波市奉化溪口·滕头旅游景区',
 16: '拉萨布达拉宫景区',
 17: '南阳市西峡伏牛山老界岭·恐龙遗址园旅游区',
 18: '宜春市明月山旅游区',
 19: '吐鲁番市葡萄沟风景区',
 20: '吉林省通化市高句丽文物古迹旅游景区',
 21: '北京八达岭－慕田峪长城旅游区',
 22: '洛阳市龙潭大峡谷景区',
 23: '南京市钟山风景名胜区·中山陵园风景区',
 24: '上海野生动物园',
 25: '山东省沂蒙山旅游区',
 26: '保山市腾冲火山热海旅游区',
 27: '桂林市独秀峰·王城景区',
 28: '江西省萍乡市武功山景区',
 29: '河南省新乡市八里沟景区',
 30: '西安市城墙·碑林历史文化景区',
 31: '崇左市德天跨国瀑布景区',
 32: '林芝市巴松措景区',
 33: '抚州市大觉山景区',
 34: '伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区',
 35: '济宁市曲阜明故城（三孔）旅游区',
 36: '武汉市东湖景区',
 37: '宣城市绩溪龙川景区',
 38: '阿坝藏族羌族自治州九寨沟旅游景区',
 39: '桂林市两江四湖·象山景区',
 40: '平遥古城',
 41: '鹰潭市龙虎山旅游景区',
 42: '贵州省黔东南州镇远古城旅游景区',
 43: '丽江市丽江古城景区',
 44: '无锡市鼋头渚景区',
 45: '六安市万佛湖景区',
 46: '岳阳市岳阳楼·君山岛景区',
 47: '乐山市峨眉山景区',
 48: '银川市镇北堡西部影视城',
 49: '无锡市灵山景区',
 50: '海南槟榔谷黎苗文化旅游区',
 51: '黑河市五大连池景区',
 52: '黄山市古徽州文化旅游区',
 53: '深圳市观澜湖休闲旅游区',
 54: '伊犁哈萨克自治州喀拉峻景区',
 55: '咸宁市赤壁市三国赤壁古战场景区',
 56: '洛阳市龙门石窟景区',
 57: '江津四面山景区',
 58: '海南呀诺达雨林文化旅游区',
 59: '贵阳市花溪青岩古镇景区',
 60: '常州市天目湖景区',
 61: '南宁市青秀山旅游区',
 62: '伊犁哈萨克自治州那拉提旅游风景区',
 63: '嘉兴市桐乡乌镇古镇旅游区',
 64: '武汉市黄鹤楼公园',
 65: '绍兴市鲁迅故里沈园景区',
 66: '邯郸市广府古城景区',
 67: '大足石刻景区',
 68: '金华市东阳横店影视城景区',
 69: '邵阳市崀山景区',
 70: '梅州市雁南飞茶田景区',
 71: '三亚市南山文化旅游区',
 72: '安顺市龙宫景区',
 73: '渭南市华山景区',
 74: '河南省洛阳栾川老君山·鸡冠洞旅游区',
 75: '嘉峪关市嘉峪关文物景区',
 76: '秦皇岛市山海关景区',
 77: '迪庆州香格里拉普拉措景区',
 78: '巫山小三峡·小小三峡',
 79: '大同市云冈石窟',
 80: '商洛市金丝峡景区',
 81: '景德镇市古窑民俗博览区',
 82: '连云港市花果山景区',
 83: '枣庄市台儿庄古城景区',
 84: '嘉兴市南湖旅游区',
 85: '开封市清明上河园',
 86: '阿坝州汶川特别旅游区',
 87: '宜昌市三峡大坝·屈原故里旅游区',
 88: '焦作市（云台山·神农山·青天河）风景名胜区',
 89: '恩施州恩施大峡谷景区',
 90: '乐山市乐山大佛景区',
 91: '镇江市金山·焦山·北固山旅游景区',
 92: '平凉市崆峒山风景名胜区',
 93: '广州市白云山风景区',
 94: '南川金佛山',
 95: '天津古文化街旅游区（津门故里）',
 96: '大丰中华麋鹿园景区',
 97: '周恩来故里旅游景区',
 98: '武汉市黄陂木兰文化生态旅游区',
 99: '赤峰市阿斯哈图石阵旅游区',
 100: '九江市庐山风景名胜区',
 101: '宁德市白水洋·鸳鸯溪旅游区',
 102: '张家界市武陵源·天门山旅游区',
 103: '重庆市彭水县阿依河景区',
 104: '广州市长隆旅游度假区',
 105: '中山市孙中山故里旅游区',
 106: '池州市九华山风景区',
 107: '安阳市殷墟景区',
 108: '黄山市黄山风景区',
 109: '南京市夫子庙·秦淮风光带景区',
 110: '新疆维吾尔自治区喀什地区帕米尔旅游区',
 111: '衢州市开化根宫佛国文化旅游景区',
 112: '西安市大雁塔·大唐芙蓉园景区',
 113: '绵阳市北川羌城旅游区',
 114: '牡丹江市镜泊湖景区',
 115: '三亚市南山大小洞天旅游区',
 116: '吉安市井冈山风景旅游区',
 117: '湖北省恩施州神龙溪纤夫文化旅游区',
 118: '西安市华清池景区',
 119: '苏州市金鸡湖景区',
 120: '烟台市龙口南山景区',
 121: '桂林市乐满地度假世界',
 122: '合肥市三河古镇景区',
 123: '烟台市蓬莱阁旅游区(三仙山·八仙过海)',
 124: '拉萨市大昭寺',
 125: '苏州市沙家浜·虞山尚湖旅游区',
 126: '山西省长治市壶关太行山大峡谷八泉峡景区',
 127: '扬州市瘦西湖风景区',
 128: '南平市武夷山风景名胜区',
 129: '湖州市南浔古镇景区',
 130: '平顶山市尧山·中原大佛景区',
 131: '佛山市西樵山景区',
 132: '洛阳市白云山景区',
 133: '天水市麦积山景区',
 134: '温州市雁荡山风景名胜区',
 135: '分界洲岛旅游区',
 136: '宝鸡市太白山旅游景区',
 137: '巴音郭楞蒙古自治州和静县巴音布鲁克景区',
 138: '长沙市花明楼景区',
 139: '泰安市泰山景区',
 140: '惠州市罗浮山景区',
 141: '厦门市鼓浪屿风景名胜区',
 142: '延边朝鲜族自治州安图县长白山景区',
 143: '中国科学院西双版纳热带植物园',
 144: '邯郸市娲皇宫景区',
 145: '新疆生产建设兵团第十师白沙湖景区',
 146: '长春市世界雕塑公园旅游景区',
 147: '舟山市普陀山风景名胜区',
 148: '江苏省无锡市惠山古镇景区',
 149: '伊春市汤旺河林海奇石景区',
 150: '惠州市惠州西湖旅游景区',
 151: '深圳市华侨城旅游度假区',
 152: '长春市伪满皇宫博物院',
 153: '日喀则市扎什伦布寺景区',
 154: '广元市剑门蜀道剑门关旅游区',
 155: '安顺市黄果树大瀑布景区',
 156: '济南市天下第一泉景区',
 157: '辽宁省盘锦市红海滩风景廊道景区',
 158: '十堰市武当山风景区',
 159: '苏州市同里古镇景区',
 160: '喀什地区喀什噶尔老城景区',
 161: '安阳市红旗渠·太行大峡谷旅游景区',
 162: '四川省雅安市碧峰峡旅游景区',
 163: '安庆市天柱山风景区',
 164: '奥林匹克公园',
 165: '昌吉回族自治州阜康市天山天池风景名胜区',
 166: '六安市天堂寨旅游景区',
 167: '故宫博物院',
 168: '满洲里市中俄边境旅游区',
 169: '海东市互助土族故土园旅游区',
 170: '延边朝鲜族自治州敦化市六鼎山文化旅游区',
 171: '陕西省延安市延安革命纪念地景区',
 172: '福建省土楼（永定·南靖）旅游景区',
 173: '伊犁哈萨克自治州阿勒泰地区喀纳斯景区',
 174: '天坛公园',
 175: '苏州园林',
 176: '湘潭市韶山旅游区',
 177: '酒泉市敦煌鸣沙山月牙泉景区',
 178: '唐山市清东陵景区',
 179: '万盛经开区黑山谷景区',
 180: '大理市崇圣寺三塔文化旅游区',
 181: '恭王府景区',
 182: '南昌市滕王阁旅游区',
 183: '中国丹霞山世界地质公园',
 184: '大连市金石滩景区',
 185: '银川市灵武水洞沟旅游区',
 186: '保定市白石山景区',
 187: '宝鸡市法门寺佛文化景区',
 188: '阳江市海陵岛大角湾海上丝路旅游区',
 189: '威海市刘公岛景区',
 190: '南充市阆中古城旅游区',
 191: '漠河市北极村旅游区',
 192: '承德市避暑山庄及周围寺庙景区',
 193: '芜湖市方特旅游区',
 194: '丽江市玉龙雪山景区',
 195: '石嘴山市沙湖旅游景区',
 196: '杭州市西湖风景名胜区',
 197: '驻马店市嵖岈山旅游景区',
 198: '保定市安新白洋淀景区',
 199: '山东省东营市黄河口生态旅游区',
 200: '酉阳桃花源旅游景区',
 201: '石家庄市西柏坡景区',
 202: '青岛市崂山景区',
 203: '徐州市云龙湖景区',
 204: '上饶市三清山旅游景区',
 205: '浙江省丽水市缙云仙都景区',
 206: '瑞金市共和国摇篮旅游区',
 207: '宜昌市长阳清江画廊景区',
 208: '喀什地区泽普金湖杨景区',
 209: '四川省甘孜州海螺沟景区',
 210: '长春市长影世纪城旅游区',
 211: '乌鲁木齐市天山大峡谷景区',
 212: '湖南省株洲市炎帝陵景区',
 213: '中央电视台无锡影视基地三国水浒景区',
 214: '嘉兴市西塘古镇旅游景区',
 215: '苏州市吴中太湖旅游区',
 216: '甘肃省张掖市七彩丹霞景区',
 217: '保定市野三坡景区',
 218: '南通市濠河景区',
 219: '云阳龙缸风景区',
 220: '沈阳市植物园',
 221: '上饶市龟峰景区',
 222: '龙岩市古田旅游区',
 223: '圆明园',
 224: '巴音郭楞蒙古自治州博斯腾湖景区',
 225: '鄂尔多斯市成吉思汗陵旅游区',
 226: '哈尔滨市太阳岛景区',
 227: '常州市环球恐龙城休闲旅游区',
 228: '延安市黄帝陵景区',
 229: '西宁市塔尔寺景区',
 230: '黔南州荔波樟江景区',
 231: '临汾市洪洞县洪洞大槐树寻根祭祖园旅游景区',
 232: '衢州市江郎山·廿八都景区',
 233: '忻州市五台山风景名胜区',
 234: '杭州市千岛湖风景名胜区',
 235: '泉州市清源山景区',
 236: '晋城市皇城相府生态文化旅游区',
 237: '上饶市婺源江湾景区',
 238: '常州市中国春秋淹城旅游区',
 239: '宜昌市三峡人家风景区',
 240: '广东省肇庆市星湖旅游景区',
 241: '忻州市雁门关景区',
 242: '台州市天台山景区',
 243: '威海市华夏城景区',
 244: '毕节市百里杜鹃景区',
 245: '颐和园',
 246: '佛山市长鹿旅游休博园',
 247: '本溪市本溪水洞景区',
 248: '盘山风景名胜区',
 249: '西安市秦始皇兵马俑博物馆',
 250: '大连市大连老虎滩海洋公园·老虎滩极地馆',
 251: '长沙市岳麓山·橘子洲旅游区',
 252: '衡阳市南岳衡山旅游区',
 253: '武隆喀斯特旅游区(天生三桥·仙女山·芙蓉洞)',
 254: '成都市青城山·都江堰旅游景区',
 255: '上海科技馆',
 256: '长春市净月潭景区',
 257: '广安市邓小平故里旅游区',
 258: '昆明市石林风景区',
 259: '神农架风景区',
 260: '三亚市蜈支洲岛旅游区',
 261: '青海湖景区',
 262: '阿坝州黄龙景区',
 263: '河北省保定市清西陵景区',
 264: '阿尔山·柴河旅游景区',
 265: '台州市神仙居景区',
 266: '广西壮族自治区百色市百色起义纪念园景区',
 267: '上海东方明珠广播电视塔',
 268: '黄山市皖南古村落·西递宏村',
 269: '中卫市沙坡头旅游景区',
 270: '镇江市句容茅山景区',
 271: '登封市嵩山少林景区',
 272: '苏州市周庄古镇景区'}

In [124]:
data_dict1 = pd.DataFrame(data = dict1,index = list(range(len(set1))),columns = ['scence_id','scence_name'])
data_dict1['scence_id'] = list(range(len(set1)))
data_dict1['scence_name'] = list(set1)

In [125]:
data_dict1

     scence_id       scence_name
0            0         福州市三坊七巷景区
1            1           桂林市漓江景区
2            2  铜仁市梵净山（江口·印江）旅游区
3            3         北京市明十三陵景区
4            4  内蒙古自治区阿拉善盟胡杨林旅游区
..         ...               ...
268        268     黄山市皖南古村落·西递宏村
269        269        中卫市沙坡头旅游景区
270        270         镇江市句容茅山景区
271        271         登封市嵩山少林景区
272        272         苏州市周庄古镇景区

[273 rows x 2 columns]

In [128]:
df9 = pd.merge(df8,data_dict1,on = 'scence_name', how = 'left')

In [129]:
df9.to_csv('E:\\论文\\第二篇论文\\截止到2023年2月数据汇总\\包含holiday_评论_月份_天气的数据集合.csv',encoding = 'utf-8-sig')